networks:
  dns:
    name: dns
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DNS_DOCKER_SUBNET:?err}.0/24
          gateway: ${DNS_DOCKER_SUBNET:?err}.1

services:
  unbound-pre-start:
    image: alpine:3.22
    container_name: unbound-pre-start
    command:
      - /bin/sh
      - -c
      - /scripts/parse_file.sh /_setup/templates/unbound.conf /opt/unbound/etc/unbound/unbound.conf
    networks:
      dns:
        ipv4_address: ${DNS_DOCKER_SUBNET:?err}.30
    volumes:
      - ${APPS_FOLDER:?err}/unbound:/opt/unbound/etc/unbound # config
      - ${APPS_FOLDER:?err}/unbound/_setup:/_setup # setup
      - ${SCRIPTS_FOLDER:?err}:/scripts # scripts
    environment:
      # setup
      - DOCKER_SUBNET=${DNS_DOCKER_SUBNET:?err}
      - INTERNAL_DOMAIN=${INTERNAL_DOMAIN:?err}
      - HOST_LAN_IP=${HOST_LAN_IP:?err}
      - CLD_IP=${CLOUD_IP:?err}
      - DNS_IP=${DNS_IP:?err}
      - GW_IP=${FIREWALL_GW_IP:?err}
      - MGMT_IP=${FIREWALL_MGMT_IP:?err}
      - SRV_IP=${FIREWALL_SRV_IP:?err}
      - HA_IP=${HOME_AUTOMATION_IP:?err}
      - IM_IP=${IMMICH_IP:?err}
      - JMP_IP=${JUMP_IP:?err}
      - MM_IP=${MEDIA_MANAGEMENT_IP:?err}
      - MS_IP=${MEDIA_SERVER_IP:?err}
      - NAS_IP=${NAS_IP:?err}
      - NTS_IP=${NOTES_IP:?err}
      - RP_IP=${REVERSE_PROXY_IP:?err}
      - SBX_IP=${SANDBOX_IP:?err}
      - VLT_IP=${VAULT_IP:?err}
      - VPN_IP=${VPN_IP:?err}
      - VSC_IP=${VSCODE_SERVER_IP:?err}
      - WB_IP=${WHITEBOARD_IP:?err}
  
  # Unbound - DNS server for local resolution
  unbound:
    image: mvance/unbound:1.22.0
    container_name: unbound
    restart: unless-stopped
    networks:
      dns:
        ipv4_address: ${DNS_DOCKER_SUBNET:?err}.10
    depends_on:
      unbound-pre-start:
        condition: service_completed_successfully
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ${APPS_FOLDER:?err}/unbound:/opt/unbound/etc/unbound # config
