networks:
  reverse-proxy:
    name: reverse-proxy
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${REVERSE_PROXY_DOCKER_SUBNET:?err}.0/24
          gateway: ${REVERSE_PROXY_DOCKER_SUBNET:?err}.1

services:
  unbound-pre-start:
    image: alpine:latest
    container_name: unbound-pre-start
    command:
      - /bin/sh
      - -c
      - /scripts/parse_file.sh /_setup/templates/unbound.conf /opt/unbound/etc/unbound/unbound.conf
    networks:
      reverse-proxy:
        ipv4_address: ${REVERSE_PROXY_DOCKER_SUBNET:?err}.30
    volumes:
      - ${APPS_FOLDER:?err}/unbound:/opt/unbound/etc/unbound # config
      - ${APPS_FOLDER:?err}/unbound/_setup:/_setup # setup
      - ${SCRIPTS_FOLDER:?err}:/scripts # scripts
    environment:
      # setup
      - DOCKER_SUBNET=${REVERSE_PROXY_DOCKER_SUBNET:?err}
      - INTERNAL_DOMAIN=${INTERNAL_DOMAIN:?err}
      - RP_HOST_IP=${REVERSE_PROXY_HOST_IP:?err}
      - CLD_HOST_IP=${CLOUD_HOST_IP:?err}
      - HA_HOST_IP=${HOME_AUTOMATION_HOST_IP:?err}
      - IM_HOST_IP=${IMMICH_HOST_IP:?err}
      - MM_HOST_IP=${MEDIA_MANAGEMENT_HOST_IP:?err}
      - MS_HOST_IP=${MEDIA_SERVER_HOST_IP:?err}
      - VLT_HOST_IP=${VAULT_HOST_IP:?err}
      - VSC_HOST_IP=${VSCODE_SERVER_HOST_IP:?err}
  
  # Unbound - DNS server for local resolution
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    networks:
      reverse-proxy:
        ipv4_address: ${REVERSE_PROXY_DOCKER_SUBNET:?err}.10
    depends_on:
      unbound-pre-start:
        condition: service_completed_successfully
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ${APPS_FOLDER:?err}/unbound:/opt/unbound/etc/unbound # config
