flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0; 
		policy drop;

		iifname lo accept
		ct state established,related accept
		ct state invalid drop
		
		# Allow ping and other ICMP control (v4/v6)
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# Allow SSH (22/tcp) from mgmt
		ip saddr 10.10.31.9 tcp dport 22 accept # from mgmt
		ip saddr 10.10.32.9 tcp dport 22 accept # from mgmt
	}

	chain forward {
		type filter hook forward priority 0; 
		policy drop;

		# Allow return traffic for forwarded flows
		ct state established,related accept

		# Allow ICMP (ping) between extern and intern
		ip saddr 10.10.31.0/24 ip daddr 10.10.32.0/24 ip protocol icmp accept
		ip saddr 10.10.32.0/24 ip daddr 10.10.31.0/24 ip protocol icmp accept

		# Allow all traffic from extern (media-server) to intern (media-management)
		ip saddr 10.10.31.11 ip daddr 10.10.32.11 accept

		# Allow NFS (2049/tcp) from extern/intern to intern (nas)
		ip saddr { 10.10.31.0/24, 10.10.32.0/24 } ip daddr 10.10.32.30 tcp dport 2049 accept
	}

	chain output {
		type filter hook output priority 0; 
		policy accept;
	}
}
