table inet filter {
	chain input {
		type filter hook input priority 0; 
		policy drop;

		iifname lo accept
		ct state established,related accept

		# Allow ping and other ICMP control (v4/v6)
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# Allow SSH (22/tcp) from mgmt
		ip saddr 10.10.32.9 tcp dport 22 accept # from mgmt
		tcp dport 22 drop # from everyone

		# Allow all ports from dmz (RP) and extern
		ip saddr 10.10.32.3 accept # from reverse proxy
		ip saddr 10.10.31.0/24 accept # from extern
	}
	
	chain output {
		type filter hook output priority 0; 
		policy accept;
	}
}
