### [!] DOMAINS
INTERNAL_DOMAIN="${INTERNAL_DOMAIN}"
EXTERNAL_DOMAIN="${EXTERNAL_DOMAIN}"

### [!] SWAG
DNSPLUGIN="${DNSPLUGIN}"

### [!] AUTHELIA
AUTHELIA_JWT_SECRET="${AUTHELIA_JWT_SECRET}"
AUTHELIA_ENCRYPTION_KEY="AUTHELIA_ENCRYPTION_KEY"
AUTHELIA_USER_NAME="${AUTHELIA_USER_NAME}"
AUTHELIA_USER_EMAIL="AUTHELIA_USER_EMAIL"
AUTHELIA_USER_PASSWORD="${AUTHELIA_USER_PASSWORD}"