## Version 2024/07/16 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/defaults/nginx/site-confs/default.conf.sample

# redirect all traffic to https
server {
    listen 80;
    listen [::]:80;

    location / {
        return 301 https://$host$request_uri;
    }
}

# main server block
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name ${EXTERNAL_DOMAIN};

    include /config/nginx/ssl.conf;

    root /config/www;
    index index.html index.htm index.php;

    location / {
        try_files $uri $uri/ /index.html /index.htm /index.php$is_args$args;
    }

    # deny access to .htaccess/.htpasswd files
    location ~ /\.ht {
        deny all;
    }
}

# enable subdomain method reverse proxy confs
include /config/nginx/proxy-confs/*.external.subdomain.conf;
