## Version 2024/07/16 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/defaults/nginx/site-confs/default.conf.sample

# redirect all traffic to https
server {
    listen 80;
    listen [::]:80;

    location / {
        return 301 https://$host$request_uri;
    }
}

# main server block
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name ${INTERNAL_DOMAIN};

    include /config/nginx/htaccess.conf;

    include /config/nginx/ssl-private.conf;

    root /config/www;
    index index.html index.htm index.php;

    # keep this page public for the internal network
    # enable for Authelia (requires authelia-location.conf in the location block)
    # include /config/authelia/authelia-server.conf;

    location / {
        # keep this page public for the internal network
		# enable for Authelia (requires authelia-server.conf in the server block)
        # include /config/authelia/authelia-location.conf;
		
        include /config/nginx/proxy.conf;
		include /config/nginx/resolver.conf;
		set $upstream_app dashboard;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location /ca {
        alias /config/www/root.crt; # Path to the directory containing your .crt file
        default_type application/octet-stream; # Serve as binary
        add_header Content-Disposition "attachment; filename=root.crt"; # Force download with a specific filename
        add_header Cache-Control "no-cache";
    }

    # deny access to .htaccess/.htpasswd files
    location ~ /\.ht {
        deny all;
    }
}

# enable subdomain method reverse proxy confs
include /config/nginx/proxy-confs/*.internal.subdomain.conf;
