services:
  environment:
    container_name: environment
    build: ../docker
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    tty: true
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/loop0:/dev/loop0"
      - "/dev/loop1:/dev/loop1"
      - "/dev/loop2:/dev/loop2"
