flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0; 
		policy drop;

		iifname lo accept
		ct state established,related accept
		ct state invalid drop
		
		# Allow ping and other ICMP control (v4/v6)
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# Allow SSH (22/tcp) from mgmt
		ip saddr 10.10.30.9 tcp dport 22 accept # from mgmt (jump)
		tcp dport 22 drop # from everyone

		# Allow Portainer (19001/tcp) from mgmt
		ip saddr 10.10.30.9 tcp dport 19001 accept # from mgmt (management)
		tcp dport 19001 drop # from everyone

		# Allow HTTPS (443/tcp) from anywhere except internal 10.10.0.0/16
		ip saddr 10.10.0.0/16 tcp dport 443 drop
		tcp dport 443 accept

		# Allow 5000 (internal https) from internal
		ip saddr 10.10.0.0/16 tcp dport 5000 accept
	}

	chain forward {
		type filter hook forward priority 0; 
		policy drop;
		
		# Forward Docker
		ip saddr 172.17.0.0/12 accept
       	ip daddr 172.17.0.0/12 accept
	}

	chain output {
		type filter hook output priority 0;
		policy accept;
	}
}
