specs:
  cores: 2
  ram_size: 2048 # MB
  disk_size: 10 # GB
  additional_disks: []
  pci_devices: []
order_tier: 2
config:
  docker: true
  router: false
  routes: 
    - network: 10.10.2.0/24 # mgmt
      via: 10.10.30.9 # firewall-mgmt
  dns_servers: [1.1.1.1, 8.8.8.8]
nics:
  - bridge: vmbr3 # srv
    trunks: 
      - id: 30 # dmz
        ipv4: 10.10.30.10/24
        gateway: 10.10.30.1
      - id: 31 # extern
        ipv4: 10.10.31.10/24
      - id: 32 # intern
        ipv4: 10.10.32.10/24
nas: null
