services:
  # SWAG - Reverse proxy with Certbot, for Let's Encrypt / ZeroSSL
  swag:
    image: lscr.io/linuxserver/swag:5.1.0
    container_name: swag
    depends_on:
      minica:
        condition: service_completed_successfully
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      reverse-proxy:
        ipv4_address: ${REVERSE_PROXY_DOCKER_SUBNET:?err}.11
    dns:
      -  ${DNS_IP:?err} # Custom DNS server (DNS VM (Unbound))
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${APPS_FOLDER:?err}/swag:/config:rw # config
      - ${APPS_FOLDER:?err}/swag/_setup:/_setup # setup
      - ${SCRIPTS_FOLDER:?err}:/scripts # scripts
    environment:
      - PROPAGATION=${DNS_PROPAGATION_TIME:?err}
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - URL=${EXTERNAL_DOMAIN:?err}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=${VALIDATION:?err}
      - DNSPLUGIN=${DNS_PROVIDER}
      - ONLY_SUBDOMAINS=${ONLY_SUBDOMAINS}
      # setup
      - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN:?err}
      - INTERNAL_DOMAIN=${INTERNAL_DOMAIN:?err}
      - DNS_PROVIDER_TOKEN=${DNS_PROVIDER_TOKEN:?err}
      # ports
      - PORT_UI_PROXMOX=${PORT_UI_PROXMOX:?err}
      - HOST_LAN_IP=${HOST_LAN_IP:?err}
      # - RP
      - PORT_UI_AUTHELIA=${PORT_UI_AUTHELIA:?err}
      # - HA
      - PORT_UI_HOME_ASSISTANT=${PORT_UI_HOME_ASSISTANT:?err}
      # - IM
      - PORT_UI_IMMICH=${PORT_UI_IMMICH:?err}
      # MGMT
      - PORT_UI_PORTAINER=${PORT_UI_PORTAINER:?err}
      - PORT_UI_HOMARR=${PORT_UI_HOMARR:?err}
      # - MM
      - PORT_UI_PROWLARR=${PORT_UI_PROWLARR:?err}
      - PORT_UI_QBITTORRENT=${PORT_UI_QBITTORRENT:?err}
      - PORT_UI_BAZARR=${PORT_UI_BAZARR:?err}
      - PORT_UI_RADARR=${PORT_UI_RADARR:?err}
      - PORT_UI_RADARR4K=${PORT_UI_RADARR4K:?err}
      - PORT_UI_SONARR=${PORT_UI_SONARR:?err}
      - PORT_UI_SONARR4K=${PORT_UI_SONARR4K:?err}
      - PORT_UI_MAINTAINERR=${PORT_UI_MAINTAINERR:?err}
      # - MS
      - PORT_UI_OVERSEERR=${PORT_UI_OVERSEERR:?err}
      - PORT_UI_SEERR=${PORT_UI_SEERR:?err}
      - PORT_UI_PLEX=${PORT_UI_PLEX:?err}
      - PORT_UI_JELLYFIN=${PORT_UI_JELLYFIN:?err}
      # - NC
      - PORT_UI_NEXTCLOUD=${PORT_UI_NEXTCLOUD:?err}
      # - VW
      - PORT_UI_VAULTWARDEN=${PORT_UI_VAULTWARDEN:?err}
      # - VSC
      - PORT_UI_VSCODE_SERVER=${PORT_UI_VSCODE_SERVER:?err}
    post_start:
      - command: /scripts/parse_folder.sh /_setup/templates /config
        user: root
        environment:
          - PUID=${PUID:?err}
          - PGID=${PGID:?err}
  
  # Minica - Generate self signed certificat
  minica:
    container_name: minica
    build:
      context: ${APPS_FOLDER:?err}/ca
      dockerfile: Dockerfile
      no_cache: true
    networks:
      reverse-proxy:
        ipv4_address: ${REVERSE_PROXY_DOCKER_SUBNET:?err}.31
    volumes:
      - ${APPS_FOLDER:?err}/ca/certs:/app/certs
      - ${APPS_FOLDER:?err}/swag/keys-private:/swag/keys-private
      - ${APPS_FOLDER:?err}/swag/www:/swag/www
    environment:
      - DOMAIN=${INTERNAL_DOMAIN}
      - ROOT_CN=${ROOT_CA_COMMON_NAME:?err}
