---
# Wait for the proxmox server to be reachable
- import_playbook: common/wait-for-connection.playbook.yml
  vars:
    target_group: homelab
# Install proxmox on raw debian
- import_playbook: proxmox/install-proxmox.playbook.yml
# Hardening debian/proxmox users
- import_playbook: proxmox/hardening.playbook.yml
# Additional configuration and setup
- import_playbook: proxmox/additional-setup.playbook.yml
# User management
- import_playbook: proxmox/setup-user.playbook.yml
