---
- name: Run on localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print a log message for localhost
      debug:
        msg: Hello from Ansible on localhost!
- name: Run on homelab
  hosts: homelab
  gather_facts: false
  tasks:
    - name: Print a log message for homelab
      debug:
        msg: Hello from Ansible on homelab!
