# deny router
deny 192.168.1.1/32;
# local network 192.168 (default)
allow 192.168.0.0/16;
# local network (notably: docker)
allow 172.16.0.0/12;
# local network 10.0
allow 10.0.0.0/8;
# localhost
allow 127.0.0.1/32;
deny all;