# yamllint disable rule:comments-indentation
---
theme: 'dark'

##
## Server Configuration
##
server:
   address: 'tcp://:9091/authelia'

##
## Log Configuration
##
log:
  level: 'debug'
  format: 'json'
  file_path: '/config/logs/authelia.log'
  keep_stdout: true

##
## Identity Validation Configuration
##
identity_validation:

  reset_password:
    jwt_secret: '${AUTHELIA_JWT_SECRET}'

##
## NTP Configuration
##
ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 4
  max_desync: '5 seconds'
  disable_startup_check: false
  disable_failure: false

##
## Authentication Backend Provider Configuration
##
authentication_backend:
  password_reset:
    disable: true

  file:
    path: '/config/users_database.yml'
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

##
## Password Policy Configuration.
##
password_policy:

  standard:
    enabled: true
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true

##
## Access Control Configuration
##
access_control:
  default_policy: 'deny'

  networks:
    - name: 'internal'
      networks:
        - '192.168.1.0/24'
        - '10.10.0.0/16'

  rules:
	# root domains are allowed for everyone
	- domain:
        - '${INTERNAL_DOMAIN}'
        - '${EXTERNAL_DOMAIN}'
      policy: 'one_factor'

	# "admin" should be allowed everywhere
	- domain:
        - '*.${INTERNAL_DOMAIN}'
        - '*.${EXTERNAL_DOMAIN}'
      subject:
        - 'group:admin'
      policy: 'one_factor'

	# "family" only have access to a set of internal apps and all external apps 
	- domain:
        - '*.${EXTERNAL_DOMAIN}'
		- auth.${INTERNAL_DOMAIN}
		- request.${INTERNAL_DOMAIN}
		- media.${INTERNAL_DOMAIN}
      subject:
        - 'group:family'
      policy: 'one_factor'

	# "user" only have access to a set of external apps
	- domain:
        # - '*.${EXTERNAL_DOMAIN}'
		- request.${EXTERNAL_DOMAIN}
		- media.${EXTERNAL_DOMAIN}
      subject:
        - 'group:user'
      policy: 'one_factor'

	# "guest" only have access to a set of internal apps
	- domain:
        - '${INTERNAL_DOMAIN}'
	  networks:
        - 'internal'
      subject:
        - 'group:guest'
      policy: 'one_factor'
    
##
## Session Provider Configuration
##
session:
   cookies:
   	# internal domain cookie
    - name: 'authelia_session'
      domain: '${INTERNAL_DOMAIN}'
      authelia_url: 'https://auth.${INTERNAL_DOMAIN}/'
      default_redirection_url: 'https://${INTERNAL_DOMAIN}/'
      inactivity: '5 minutes'
      expiration: '1 hour'
      remember_me: '1 month'

   	# external domain cookie
	- name: 'authelia_session'
	  domain: '${EXTERNAL_DOMAIN}'
	  authelia_url: 'https://auth.${EXTERNAL_DOMAIN}/'
	  default_redirection_url: 'https://${EXTERNAL_DOMAIN}/'
	  inactivity: '5 minutes'
	  expiration: '1 hour'
	  remember_me: '1 month'

  name: 'authelia_session'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'

##
## Storage Provider Configuration
##
storage:
  encryption_key: '${AUTHELIA_ENCRYPTION_KEY}'
  local:
    path: '/config/db.sqlite3'

##
## Notification Provider
##
notifier:
  filesystem:
    filename: '/config/logs/notification.txt'

##
## Identity Providers
##
identity_providers:
  oidc:
    hmac_secret: 'this_is_a_secret_abc123abc123abc'
    jwks:
      - algorithm: 'RS256'
        use: 'sig'
        key: |
          # -----BEGIN RSA PRIVATE KEY-----
          # ...
          # -----END RSA PRIVATE KEY-----

    clients:
      - client_id: 'homarr'
        client_name: 'homarr'
		# The digest of 'insecure_secret'.
        client_secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'  
        redirect_uris:
          - 'https://hgomarr.${INTERNAL_DOMAIN}:8080/oauth2/callback'
        scopes:
          - 'openid'
          - 'groups'
          - 'email'
          - 'profile'
        authorization_policy: 'one_factor'
