# yamllint disable rule:comments-indentation
---
theme: 'dark'

##
## Server Configuration
##
server:
  address: 'tcp://:9091/authelia'

##
## Log Configuration
##
log:
  level: 'trace'
  format: 'json'
  file_path: '/config/logs/authelia.log'
  keep_stdout: true

##
## Identity Validation Configuration
##
identity_validation:
  reset_password:
    jwt_secret: '${AUTHELIA_JWT_SECRET}'

##
## NTP Configuration
##
ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 4
  max_desync: '5 seconds'
  disable_startup_check: false
  disable_failure: false

##
## Authentication Backend Provider Configuration
##
authentication_backend:
  password_reset:
    disable: true

  file:
    path: '/config/users_database.yml'
    watch: true
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

##
## Password Policy Configuration.
##
password_policy:
  standard:
    enabled: true
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true

##
## Access Control Configuration
##
access_control:
  default_policy: 'deny'

  networks:
    - name: 'internal'
      networks:
        - '192.168.1.0/24'
        - '10.10.0.0/16'

  rules:
    # root domains are allowed for everyone
    - domain:
        - '${INTERNAL_DOMAIN}'
        - '${EXTERNAL_DOMAIN}'
      policy: 'one_factor'

    # "admin" should be allowed everywhere
    - domain:
        - '*.${INTERNAL_DOMAIN}'
        - '*.${EXTERNAL_DOMAIN}'
      subject:
        - 'group:admin'
      policy: 'one_factor'

    # "family" only have access to a set of internal apps and all external apps 
    - domain:
        - '*.${EXTERNAL_DOMAIN}'
        - auth.${INTERNAL_DOMAIN}
        - request.${INTERNAL_DOMAIN}
        - media.${INTERNAL_DOMAIN}
      subject:
        - 'group:family'
      policy: 'one_factor'

    # "user" only have access to a set of external apps
    - domain:
        # - '*.${EXTERNAL_DOMAIN}'
        - auth.${EXTERNAL_DOMAIN}
        - request.${EXTERNAL_DOMAIN}
        - media.${EXTERNAL_DOMAIN}
      subject:
        - 'group:user'
      policy: 'one_factor'

    # "guest" only have access to a set of internal apps
    - domain:
        - '${INTERNAL_DOMAIN}'
      networks:
        - 'internal'
      subject:
        - 'group:guest'
      policy: 'one_factor'
    
##
## Session Provider Configuration
##
session:
  cookies:
    # internal domain cookie
    - name: 'authelia_session'
      domain: '${INTERNAL_DOMAIN}'
      authelia_url: 'https://auth.${INTERNAL_DOMAIN}/'
      default_redirection_url: 'https://${INTERNAL_DOMAIN}/'
      inactivity: '5 minutes'
      expiration: '1 hour'
      remember_me: '1 month'

    # external domain cookie
    - name: 'authelia_session'
      domain: '${EXTERNAL_DOMAIN}'
      authelia_url: 'https://auth.${EXTERNAL_DOMAIN}/'
      default_redirection_url: 'https://${EXTERNAL_DOMAIN}/'
      inactivity: '5 minutes'
      expiration: '1 hour'
      remember_me: '1 month'

  name: 'authelia_session'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'

##
## Storage Provider Configuration
##
storage:
  encryption_key: '${AUTHELIA_ENCRYPTION_KEY}'
  local:
    path: '/config/db.sqlite3'

##
## Notification Provider
##
notifier:
  filesystem:
    filename: '/config/logs/notification.txt'

##
## Identity Providers
##
identity_providers:
  oidc:
    hmac_secret: '${AUTHELIA_OIDC_HMAC_SECRET}'
    jwks:
      - algorithm: 'RS256'
        use: 'sig'
        key: {{ "${AUTHELIA_OIDC_JWKS_KEY}" | b64dec | mindent 10 "|" | msquote }}

    clients:
      - client_id: 'homarr'
        client_name: 'homarr'
        client_secret: '${HOMARR_OIDC_CLIENT_SECRET}'  
        redirect_uris:
          - 'https://homarr.${INTERNAL_DOMAIN}/api/auth/callback/oidc'
        scopes:
          - 'openid'
          - 'email'
          - 'groups'
          - 'profile'
        authorization_policy: 'one_factor'
        userinfo_signed_response_alg: 'none'
        consent_mode: implicit

      - client_id: 'portainer'
        client_name: 'portainer'
        client_secret: '${PORTAINER_OIDC_CLIENT_SECRET}'
        redirect_uris:
          - 'https://portainer.${INTERNAL_DOMAIN}'
        scopes:
          - 'openid'
          - 'email'
          - 'groups'
          - 'profile'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        authorization_policy: 'one_factor'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
        consent_mode: implicit
      
      - client_id: 'jellyfin'
        client_name: 'jellyfin'
        client_secret: '${JELLYFIN_OIDC_CLIENT_SECRET}'
        redirect_uris:
          - 'https://jellyfin.${INTERNAL_DOMAIN}/sso/OID/redirect/authelia'
        scopes:
          - 'openid'
          - 'email'
          - 'groups'
          - 'profile'
        authorization_policy: 'one_factor'
        token_endpoint_auth_method: 'client_secret_post'
        consent_mode: implicit

      - client_id: 'jellyfin-external'
        client_name: 'jellyfin-external'
        client_secret: '${JELLYFIN_EXTERNAL_OIDC_CLIENT_SECRET}'
        redirect_uris:
          - 'https://jellyfin.${EXTERNAL_DOMAIN}/sso/OID/redirect/authelia-external'
        scopes:
          - 'openid'
          - 'email'
          - 'groups'
          - 'profile'
        authorization_policy: 'one_factor'
        token_endpoint_auth_method: 'client_secret_post'
        consent_mode: implicit

      - client_id: 'yamtrack'
        client_name: 'yamtrack'
        client_secret: '${YAMTRACK_OIDC_CLIENT_SECRET}'
        redirect_uris:
          - 'https://yamtrack.${INTERNAL_DOMAIN}/accounts/oidc/authelia/login/callback/'
        scopes:
          - 'openid'
          - 'email'
          - 'groups'
          - 'profile'
        authorization_policy: 'one_factor'
        consent_mode: implicit

      - client_id: 'yamtrack-external'
        client_name: 'yamtrack-external'
        client_secret: '${YAMTRACK_EXTERNAL_OIDC_CLIENT_SECRET}'
        redirect_uris:
          - 'https://yamtrack.${EXTERNAL_DOMAIN}/accounts/oidc/authelia-external/login/callback/'
        scopes:
          - 'openid'
          - 'email'
          - 'groups'
          - 'profile'
        authorization_policy: 'one_factor'
        consent_mode: implicit
