### [!] GLOBAL
INTERNAL_DOMAIN="${INTERNAL_DOMAIN}"

### [!] PORTAINER
PORTAINER_ADMIN_PASSWORD_ENCRYPTED='password_bcrypt(${users.ADMIN_PASSWORD})'
PORTAINER_ADMIN_PASSWORD='${users.ADMIN_PASSWORD}'
PORTAINER_OIDC_CLIENT_SECRET="${PORTAINER_OIDC_CLIENT_SECRET}"

### [!] HOMARR
HOMARR_SECRET_ENCRYPTION_KEY="${HOMARR_SECRET_ENCRYPTION_KEY}"
HOMARR_OIDC_CLIENT_SECRET="${HOMARR_OIDC_CLIENT_SECRET}"

### [!] MEDIA_MANAGEMENT
# For homarr config
API_KEY_PROWLARR="${media-management.API_KEY_PROWLARR}"
API_KEY_BAZARR="${media-management.API_KEY_BAZARR}"
API_KEY_RADARR="${media-management.API_KEY_RADARR}"
API_KEY_RADARR4K="${media-management.API_KEY_RADARR4K}"
API_KEY_SONARR="${media-management.API_KEY_SONARR}"
API_KEY_SONARR4K="${media-management.API_KEY_SONARR4K}"

### [!] MEDIA_SERVER
# For homarr config
# API_KEY_OVERSEERR="${media-server.API_KEY_OVERSEERR}"
# PLEX_CLAIM="${media-server.PLEX_CLAIM}"
