### [!] GLOBAL
INTERNAL_DOMAIN="${INTERNAL_DOMAIN}"

### [!] VPN
VPN_SERVICE_PROVIDER="${VPN_SERVICE_PROVIDER}"
VPN_USERNAME="${VPN_USERNAME}"
VPN_PASSWORD="${VPN_PASSWORD}"

### [!] API KEY SEEDS
API_KEY_PROWLARR="${API_KEY_PROWLARR}"
API_KEY_BAZARR="${API_KEY_BAZARR}"
API_KEY_RADARR="${API_KEY_RADARR}"
API_KEY_RADARR4K="${API_KEY_RADARR4K}"
API_KEY_SONARR="${API_KEY_SONARR}"
API_KEY_SONARR4K="${API_KEY_SONARR4K}"
# API_KEY_MAINTAINERR="${API_KEY_MAINTAINERR}"

### [!] BAZARR
OPENSUBTITLE_USERNAME="${OPENSUBTITLE_USERNAME}"
OPENSUBTITLE_PASSWORD="${OPENSUBTITLE_PASSWORD}"

### [!] PROWLARR
SHAREWOOD_PASSKEY="${SHAREWOOD_PASSKEY}"
