# General
PROXMOX_API_URL="https://${infra.IP_SERVER}:8006"
PROXMOX_NODE="home"
PROXMOX_DATASTORE_ID="local"
PROXMOX_VM_TEMPLATE_NAME="vm-alpine-template"
PROXMOX_VM_TEMPLATE_ID="9000"

# Ansible - setup proxmox
PROXMOX_ADMIN_PASSWORD="${PROXMOX_ADMIN_PASSWORD}"
PACKER_PASSWORD="${PROXMOX_PACKER_PASSWORD}"
TERRAFORM_PASSWORD="${PROXMOX_TERRAFORM_PASSWORD}"
IP_NAMESERVER="${infra.IP_NAMESERVER}"

# Packer
CONTROL_NODE_IP="${infra.IP_CONTROL_NODE}"
SSH_ROOT_PASSWORD="${PROXMOX_TEMPLATE_ROOT_PASSWORD}"
KEYBOARD_LAYOUT="${KEYBOARD_LAYOUT}"

# Terraform
