networks:
  management:
    name: management
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${MANAGEMENT_DOCKER_SUBNET:?err}.0/24
          gateway: ${MANAGEMENT_DOCKER_SUBNET:?err}.1

services:
  portainer-pre-start:
    image: alpine:3.22
    container_name: portainer-pre-start
    networks:
      management:
        ipv4_address: ${MANAGEMENT_DOCKER_SUBNET:?err}.30
    command:
      - /bin/sh
      - -c
      - /scripts/parse_file.sh /_setup/templates/config.json /data/config.json
    volumes:
      - ${APPS_FOLDER:?err}/portainer:/data # config
      - ${APPS_FOLDER:?err}/portainer/_setup:/_setup # setup
      - ${SCRIPTS_FOLDER:?err}:/scripts # scripts
    environment:
      # setup
      - CLD_IP=${CLOUD_IP:?err}
      - DNS_IP=${DNS_IP:?err}
      - HA_IP=${HOME_AUTOMATION_IP:?err}
      - IM_IP=${IMMICH_IP:?err}
      - MM_IP=${MEDIA_MANAGEMENT_IP:?err}
      - MS_IP=${MEDIA_SERVER_IP:?err}
      - NTS_IP=${NOTES_IP:?err}
      - RP_IP=${REVERSE_PROXY_IP:?err}
      - SBX_IP=${SANDBOX_IP:?err}
      - VLT_IP=${VAULT_IP:?err}
      - VPN_IP=${VPN_IP:?err}
      - VSC_IP=${VSCODE_SERVER_IP:?err}
      - WB_IP=${WHITEBOARD_IP:?err}
  
  # Portainer - Remote Docker container management
  portainer:
    image: portainer/portainer-ce:2.35.0-alpine
    container_name: portainer
    restart: unless-stopped
    networks:
      management:
        ipv4_address: ${MANAGEMENT_DOCKER_SUBNET:?err}.10
    depends_on:
      portainer-pre-start:
        condition: service_completed_successfully
    command:
      - "--hide-labels"
      - "--templates"
      - "https://raw.githubusercontent.com/portainer/templates/master/templates-2.0.json"
    ports:
      - "${PORT_UI_PORTAINER:?err}:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPS_FOLDER:?err}/portainer:/data
    environment:
      - LOG_LEVEL=info

  # Homarr - Application Dashboard
  homarr:
    image: ghcr.io/homarr-labs/homarr:v1.41.0
    container_name: homarr
    restart: unless-stopped
    networks:
      media-management:
        ipv4_address: ${MEDIA_MANAGEMENT_DOCKER_SUBNET:?err}.11
    ports:
      - ${PORT_UI_HOMARR:?err}:7575
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPS_FOLDER:?err}/homarr/configs:/app/data/configs # config
      - ${APPS_FOLDER:?err}/homarr/data:/data # data
      - ${APPS_FOLDER:?err}/homarr/_setup:/_setup # setup
      - ${APPS_FOLDER:?err}/homarr/icons:/app/public/icons
      - ${SCRIPTS_FOLDER:?err}:/scripts # scripts
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      # setup
      - DOCKER_SUBNET=${MEDIA_MANAGEMENT_DOCKER_SUBNET:?err}
      - DOMAIN=${INTERNAL_DOMAIN:?err}
      - MS_HOST_IP=${MEDIA_SERVER_IP:?err}
      - PORT_UI_OVERSEERR=${PORT_UI_OVERSEERR:?err}
      - API_KEY_OVERSEERR=${API_KEY_OVERSEERR:?err}
      - PORT_UI_RADARR=${PORT_UI_RADARR:?err}
      - API_KEY_RADARR=${API_KEY_RADARR:?err}
      - PORT_UI_RADARR4K=${PORT_UI_RADARR4K:?err}
      - API_KEY_RADARR4K=${API_KEY_RADARR4K:?err}
      - PORT_UI_SONARR=${PORT_UI_SONARR:?err}
      - API_KEY_SONARR=${API_KEY_SONARR:?err}
      - PORT_UI_SONARR4K=${PORT_UI_SONARR4K:?err}
      - API_KEY_SONARR4K=${API_KEY_SONARR4K:?err}
      - API_KEY_PROWLARR=${API_KEY_PROWLARR:?err}
      - PORT_UI_PROWLARR=${PORT_UI_PROWLARR:?err}
      - PORT_UI_QBITTORRENT=${PORT_UI_QBITTORRENT:?err}
    post_start:
      - command: /scripts/parse_file.sh /_setup/templates/default.json /app/data/configs/default.json
        user: root
        environment:
          - PUID=${PUID:?err}
          - PGID=${PGID:?err}
