flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0; 
		policy drop;

		iifname lo accept
		ct state established,related accept
		ct state invalid drop
		
		# Allow ping and other ICMP control (v4/v6)
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# Allow SSH (22/tcp) from mgmt (jump)
		ip saddr 10.10.2.10 tcp dport 22 accept # from jump
		tcp dport 22 drop # from everyone

		# Allow all from RP (filtering done in firewall-mgmt)
		ip saddr 10.10.30.10 accept # from dmz (reverse proxy)
	}

	chain forward {
		type filter hook forward priority 0; 
		policy drop;
		
		# Forward Docker
		ip saddr 172.17.0.0/12 accept
       	ip daddr 172.17.0.0/12 accept
	}

	chain output {
		type filter hook output priority 0; 
		policy accept;
	}
}
