### [!] DOMAINS
INTERNAL_DOMAIN="${INTERNAL_DOMAIN}"
EXTERNAL_DOMAIN="${EXTERNAL_DOMAIN}"
HOST_LAN_IP="${infra.IP_SERVER}"

### [!] SWAG
DNS_PROVIDER="${DNS_PROVIDER}"
DNS_PROVIDER_TOKEN="${DNS_PROVIDER_TOKEN}"
DNS_PROPAGATION_TIME="${DNS_PROPAGATION_TIME}"
EXTRA_DOMAINS="*.sandbox.${EXTERNAL_DOMAIN}"

### [!] AUTHELIA
## config
AUTHELIA_JWT_SECRET="${AUTHELIA_JWT_SECRET}"
AUTHELIA_ENCRYPTION_KEY="${AUTHELIA_ENCRYPTION_KEY}"
AUTHELIA_OIDC_HMAC_SECRET="${AUTHELIA_OIDC_HMAC_SECRET}"
AUTHELIA_OIDC_JWKS_KEY="${AUTHELIA_OIDC_JWKS_KEY}"
## users
AUTHELIA_ADMIN_PASSWORD='password_argon(${users.ADMIN_PASSWORD})'
AUTHELIA_USERS='${users.USERS}'
## oidc clients
HOMARR_OIDC_CLIENT_SECRET='hash_argon(${management.HOMARR_OIDC_CLIENT_SECRET})'
PORTAINER_OIDC_CLIENT_SECRET='hash_argon(${management.PORTAINER_OIDC_CLIENT_SECRET})'

### [!] DDNS-UPDATER
CLOUDFLARE_ZONE_ID="${CLOUDFLARE_ZONE_ID}"
