### [!] DOMAINS
INTERNAL_DOMAIN="${INTERNAL_DOMAIN}"
EXTERNAL_DOMAIN="${EXTERNAL_DOMAIN}"

### [!] SWAG
DNS_PROVIDER="${DNS_PROVIDER}"
DNS_PROVIDER_TOKEN="${DNS_PROVIDER_TOKEN}"

### [!] AUTHELIA
AUTHELIA_JWT_SECRET="${AUTHELIA_JWT_SECRET}"
AUTHELIA_ENCRYPTION_KEY="${AUTHELIA_ENCRYPTION_KEY}"
AUTHELIA_USER_NAME="${AUTHELIA_USER_NAME}"
AUTHELIA_USER_EMAIL="${AUTHELIA_USER_EMAIL}"
AUTHELIA_USER_PASSWORD='password_argon(${AUTHELIA_USER_PASSWORD})'
