table inet filter {
	chain input {
		type filter hook input priority 0; 
		policy drop;

		iifname lo accept
		ct state established,related accept

		# Allow ping and other ICMP control (v4/v6)
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# Allow SSH (22/tcp) from mgmt
		ip saddr 10.10.1.9 tcp dport 22 accept # from mgmt

		# Allow DNS (53/tcp, 53/udp) from anywhere
		tcp dport 53 accept
		udp dport 53 accept
	}

	chain output {
		type filter hook output priority 0; 
		policy accept;
	}
}
