flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0; 
		policy drop;

		iifname lo accept
		ct state established,related accept
		ct state invalid drop
		
		# Allow ping and other ICMP control (v4/v6)
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# Allow SSH (22/tcp) from mgmt
		ip saddr 10.10.1.9 tcp dport 22 accept # from mgmt (jump)

		# Allow Portainer (19001/tcp) from mgmt
		ip saddr 10.10.1.9 tcp dport 19001 accept # from mgmt (management)
		
		# Allow DNS (53/tcp, 53/udp) from anywhere (unbound)
		tcp dport 53 accept
		udp dport 53 accept
		
		# Allow DNS (5300/tcp, 5300/udp) from anywhere (adguard)
		tcp dport 5300 accept
		udp dport 5300 accept
	}

	chain forward {
		type filter hook forward priority 0; 
		policy drop;
		
		# Forward Docker
		ip saddr 172.17.0.0/12 accept
       	ip daddr 172.17.0.0/12 accept
	}

	chain output {
		type filter hook output priority 0; 
		policy accept;
	}
}
