specs:
  cores: 1
  ram_size: 1024 # MB
  disk_size: 5 # GB
  additional_disks: []
  pci_devices: []
order_tier: 1
config:
  docker: true
  router: false
  routes: []
  dns_servers: [1.1.1.1, 8.8.8.8]
nics:
  - bridge: vmbr1 # gw
    ipv4: 10.10.1.200/24
    gateway: 10.10.1.2
nas: null
