### [!] GLOBAL
INTERNAL_DOMAIN="${INTERNAL_DOMAIN}"
EXTERNAL_DOMAIN="${EXTERNAL_DOMAIN}"

### [!] PLEX
PLEX_CLAIM="${PLEX_CLAIM}"
PLEX_USERNAME="${PLEX_USERNAME}"
PLEX_EMAIL="${PLEX_EMAIL}"
PLEX_MACHINE_IDENTIFIER="${PLEX_MACHINE_IDENTIFIER}"
PLEX_FRIENDLY_NAME="${PLEX_FRIENDLY_NAME}"

### [!] API KEY SEEDS
API_KEY_OVERSEERR="${API_KEY_OVERSEERR}"

### [!] MEDIA_MANAGEMENT
API_KEY_RADARR="${media-management.API_KEY_RADARR}"
API_KEY_RADARR4K="${media-management.API_KEY_RADARR4K}"
API_KEY_SONARR="${media-management.API_KEY_SONARR}"
API_KEY_SONARR4K="${media-management.API_KEY_SONARR4K}"
