INTERNAL_DOMAIN="${INTERNAL_DOMAIN}"
EXTERNAL_DOMAIN="${EXTERNAL_DOMAIN}"

PLEX_CLAIM="${PLEX_CLAIM}"
PLEX_USERNAME="${PLEX_USERNAME}"
PLEX_EMAIL="${PLEX_EMAIL}"
PLEX_MACHINE_IDENTIFIER="${PLEX_MACHINE_IDENTIFIER}"
PLEX_FRIENDLY_NAME="${PLEX_FRIENDLY_NAME}"

API_KEY_OVERSEERR="${API_KEY_OVERSEERR}"
API_KEY_RADARR="${API_KEY_RADARR}"
API_KEY_RADARR4K="${API_KEY_RADARR4K}"
API_KEY_SONARR="${API_KEY_SONARR}"
API_KEY_SONARR4K="${API_KEY_SONARR4K}"
