networks:
  home-automation:
    name: home-automation
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${HOME_AUTOMATION_DOCKER_SUBNET:?err}.0/24
          gateway: ${HOME_AUTOMATION_DOCKER_SUBNET:?err}.1
services:
  # Portainer Agent - for remote portainer management
  portainer-agent:
    image: portainer/agent:2.35.0-alpine
    container_name: ha-portainer-agent
    restart: unless-stopped
    networks:
      home-automation:
        ipv4_address: ${HOME_AUTOMATION_DOCKER_SUBNET:?err}.9
    ports:
      - "${PORTAINER_AGENT_PORT:-19001}:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer-agent
      - CAP_HOST_MANAGEMENT=1
