BEGIN TRANSACTION;

DELETE FROM RootFolders;
INSERT INTO RootFolders VALUES(1,'/downloads/','music',1,1,0,replace('[\n  1\n]','\n',char(10)),0);


DELETE FROM Tags;
INSERT INTO Tags VALUES(1,'music');

DELETE FROM Users;
INSERT INTO Users VALUES(1,'04ae3c57-e2b4-44c9-b8cc-ff9279182d95','dgladieux','N73lZYXs+pLcVxrEsI3wFlQsQHSlpHBf/ouSfSx6KvE=','UBq17qCFr0qhXIoR5U5n8A==',10000);

DELETE FROM MetadataProfiles;
INSERT INTO MetadataProfiles VALUES(1,'Standard',replace('[\n  {\n    "primaryAlbumType": 2,\n    "allowed": false\n  },\n  {\n    "primaryAlbumType": 4,\n    "allowed": false\n  },\n  {\n    "primaryAlbumType": 1,\n    "allowed": false\n  },\n  {\n    "primaryAlbumType": 3,\n    "allowed": false\n  },\n  {\n    "primaryAlbumType": 0,\n    "allowed": true\n  }\n]','\n',char(10)),replace('[\n  {\n    "secondaryAlbumType": 0,\n    "allowed": true\n  },\n  {\n    "secondaryAlbumType": 3,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 2,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 7,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 9,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 6,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 4,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 8,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 10,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 1,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 11,\n    "allowed": false\n  }\n]','\n',char(10)),replace('[\n  {\n    "releaseStatus": 3,\n    "allowed": false\n  },\n  {\n    "releaseStatus": 1,\n    "allowed": false\n  },\n  {\n    "releaseStatus": 0,\n    "allowed": true\n  },\n  {\n    "releaseStatus": 2,\n    "allowed": false\n  }\n]','\n',char(10)));
INSERT INTO MetadataProfiles VALUES(2,'None',replace('[\n  {\n    "primaryAlbumType": 2,\n    "allowed": false\n  },\n  {\n    "primaryAlbumType": 4,\n    "allowed": false\n  },\n  {\n    "primaryAlbumType": 1,\n    "allowed": false\n  },\n  {\n    "primaryAlbumType": 3,\n    "allowed": false\n  },\n  {\n    "primaryAlbumType": 0,\n    "allowed": false\n  }\n]','\n',char(10)),replace('[\n  {\n    "secondaryAlbumType": 0,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 3,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 2,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 7,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 9,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 6,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 4,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 8,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 10,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 1,\n    "allowed": false\n  },\n  {\n    "secondaryAlbumType": 11,\n    "allowed": false\n  }\n]','\n',char(10)),replace('[\n  {\n    "releaseStatus": 3,\n    "allowed": false\n  },\n  {\n    "releaseStatus": 1,\n    "allowed": false\n  },\n  {\n    "releaseStatus": 0,\n    "allowed": false\n  },\n  {\n    "releaseStatus": 2,\n    "allowed": false\n  }\n]','\n',char(10)));
INSERT INTO MetadataProfiles VALUES(3,'Everything',replace('[\n  {\n    "primaryAlbumType": 4,\n    "allowed": true\n  },\n  {\n    "primaryAlbumType": 3,\n    "allowed": true\n  },\n  {\n    "primaryAlbumType": 2,\n    "allowed": true\n  },\n  {\n    "primaryAlbumType": 1,\n    "allowed": true\n  },\n  {\n    "primaryAlbumType": 0,\n    "allowed": true\n  }\n]','\n',char(10)),replace('[\n  {\n    "secondaryAlbumType": 11,\n    "allowed": true\n  },\n  {\n    "secondaryAlbumType": 10,\n    "allowed": true\n  },\n  {\n    "secondaryAlbumType": 9,\n    "allowed": true\n  },\n  {\n    "secondaryAlbumType": 8,\n    "allowed": true\n  },\n  {\n    "secondaryAlbumType": 7,\n    "allowed": true\n  },\n  {\n    "secondaryAlbumType": 6,\n    "allowed": true\n  },\n  {\n    "secondaryAlbumType": 4,\n    "allowed": true\n  },\n  {\n    "secondaryAlbumType": 3,\n    "allowed": true\n  },\n  {\n    "secondaryAlbumType": 2,\n    "allowed": true\n  },\n  {\n    "secondaryAlbumType": 1,\n    "allowed": true\n  },\n  {\n    "secondaryAlbumType": 0,\n    "allowed": true\n  }\n]','\n',char(10)),replace('[\n  {\n    "releaseStatus": 3,\n    "allowed": true\n  },\n  {\n    "releaseStatus": 2,\n    "allowed": true\n  },\n  {\n    "releaseStatus": 1,\n    "allowed": true\n  },\n  {\n    "releaseStatus": 0,\n    "allowed": true\n  }\n]','\n',char(10)));

DELETE FROM NamingConfig;
INSERT INTO NamingConfig VALUES(1,1,'{Artist Name}',0,'{Album Title} ({Release Year})/{Artist Name} - {Album Title} - {track:00} - {Track Title}','{Album Title} ({Release Year})/{Medium Format} {medium:00}/{Artist Name} - {Album Title} - {track:00} - {Track Title}',4);

DELETE FROM DownloadClients;
INSERT INTO DownloadClients VALUES(1,1,'qBittorrent','QBittorrent',replace('{\n  "host": "${DOCKER_SUBNET}.10",\n  "port": ${PORT_UI_QBITTORRENT},\n  "useSsl": false,\n  "username": "admin",\n  "password": "admin!",\n  "musicCategory": "music",\n  "recentMusicPriority": 0,\n  "olderMusicPriority": 0,\n  "initialState": 0,\n  "sequentialOrder": false,\n  "firstAndLast": false,\n  "contentLayout": 0\n}','\n',char(10)),'QBittorrentSettings',1,1,1,'[]');

COMMIT;
