services:
  # Yamtrack - Media tracker / watchlist
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack:0.24
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: ${MEDIA_SERVER_DOCKER_SUBNET:?err}.22
    depends_on:
      - yamtrack-redis
    ports:
      - ${PORT_UI_YAMTRACK:?err}:8000
    volumes:
      - ${APPS_FOLDER:?err}/yamtrack/db:/yamtrack/db
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - SECRET=longstring
      - REDIS_URL=redis://yamtrack-redis:6379

  yamtrack-redis:
    container_name: yamtrack-redis
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: ${MEDIA_SERVER_DOCKER_SUBNET:?err}.32
    volumes:
      - ${APPS_FOLDER:?err}/yamtrack/redis:/data
