networks:
  media-server:
    name: media-server
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${MEDIA_SERVER_DOCKER_SUBNET:?err}.0/24
          gateway: ${MEDIA_SERVER_DOCKER_SUBNET:?err}.1
services:
  # Overseer - Media Management
  overseerr:
    image: lscr.io/linuxserver/overseerr:1.34.0
    container_name: overseerr
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: ${MEDIA_SERVER_DOCKER_SUBNET:?err}.20
    user: ${PUID:?err}:${PGID:?err}
    ports:
      - ${PORT_UI_OVERSEERR:?err}:5055
    volumes:
      - ${APPS_FOLDER:?err}/overseerr/config:/config # config
      - ${APPS_FOLDER:?err}/overseerr/_setup:/_setup # setup
      - ${SCRIPTS_FOLDER:?err}:/scripts # scripts
    environment:
      - LOG_LEVEL=debug
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:readarr
      - TP_THEME=${TP_THEME:?err}
      # setup
      - API_KEY_OVERSEERR=${API_KEY_OVERSEERR:?err}
      - DOCKER_SUBNET=${MEDIA_SERVER_DOCKER_SUBNET:?err}
      - MM_HOST_IP=${MEDIA_MANAGEMENT_IP:?err}
      - PORT_UI_PLEX=${PORT_UI_PLEX:?err}
      - PORT_UI_RADARR4K=${PORT_UI_RADARR4K:?err}
      - API_KEY_RADARR4K=${API_KEY_RADARR4K:?err}
      - PORT_UI_RADARR=${PORT_UI_RADARR:?err}
      - API_KEY_RADARR=${API_KEY_RADARR:?err}
      - PORT_UI_SONARR=${PORT_UI_SONARR:?err}
      - API_KEY_SONARR=${API_KEY_SONARR:?err}
      - PORT_UI_SONARR4K=${PORT_UI_SONARR4K:?err}
      - API_KEY_SONARR4K=${API_KEY_SONARR4K:?err}
      - WEBHOOK_OVERSERRR_DISCORD=${WEBHOOK_OVERSERRR_DISCORD} # optional
    devices:
      - /dev/dri:/dev/dri
    post_start:
      - command: /scripts/parse_file.sh /_setup/templates/settings.json /config/settings.json
        user: root
        environment:
          - PUID=${PUID:?err}
          - PGID=${PGID:?err}
  
  # Plex - Media Server
  plex:
    image: lscr.io/linuxserver/plex:1.42.2
    container_name: plex
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: ${MEDIA_SERVER_DOCKER_SUBNET:?err}.10
        # Add Configurations for GPU Hardware Rendering Here:
        #    devices:
        #      - /dev/dri/renderD128:/dev/dri/renderD128
        #      - /dev/dri/card0:/dev/dri/card0
        #      - /dev/dri:/dev/dri
        # Add this option to your run command if you plan on using Quicksync hardware acceleration - see Application Setup section.
    user: ${PUID:?err}:${PGID:?err}
    ports:
      - ${PORT_UI_PLEX:?err}:32400
      - 1900:1900/udp
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - ${APPS_FOLDER:?err}/plex:/config # config
      - ${DATA_FOLDER:?err}/media:/data/media # data
      - ${APPS_FOLDER:?err}/plex/_setup:/_setup # setup
      - ${SCRIPTS_FOLDER:?err}:/scripts # scripts
    environment:
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - VERSION=docker
      # setup
      - LAN_IP=${HOST_LAN_IP:?err}
      - PORT_UI_PLEX=${PORT_UI_PLEX:?err}
      - INTERNAL_DOMAIN=${INTERNAL_DOMAIN:?err}
      - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN:?err}
      - PLEX_CLAIM=${PLEX_CLAIM:?err}
      - PLEX_USERNAME=${PLEX_USERNAME:?err}
      - PLEX_EMAIL=${PLEX_EMAIL:?err}
      - PLEX_MACHINE_IDENTIFIER=${PLEX_MACHINE_IDENTIFIER:?err}
      - PLEX_FRIENDLY_NAME=${PLEX_FRIENDLY_NAME:?err}
    post_start:
      - command: /scripts/parse_file.sh /_setup/templates/Preferences.xml "/config/Library/Application Support/Plex Media Server/Preferences.xml"
        user: root
        environment:
          - PUID=${PUID:?err}
          - PGID=${PGID:?err}
      - command: /scripts/execute_sql.sh "/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db"
        user: root

  # Portainer Agent - for remote portainer management
  portainer-agent:
    image: portainer/agent:2.35.0-alpine
    container_name: portainer-agent
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: ${MEDIA_SERVER_DOCKER_SUBNET:?err}.09
    ports:
      - "19001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer-agent
      - CAP_HOST_MANAGEMENT=1
