services:
  # Bazarr - Subtitle library
  bazarr:
    image: lscr.io/linuxserver/bazarr:1.5.3
    container_name: bazarr
    restart: unless-stopped
    networks:
      media-management:
        ipv4_address: ${MEDIA_MANAGEMENT_DOCKER_SUBNET:?err}.21
    user: ${PUID:?err}:${PGID:?err}
    ports:
      - ${PORT_UI_BAZARR:?err}:6767
    volumes:
      - ${APPS_FOLDER:?err}/bazarr:/config # config
      - ${DATA_FOLDER:?err}:/data # data
      - ${APPS_FOLDER:?err}/bazarr/_setup:/_setup # setup
      - ${SCRIPTS_FOLDER:?err}:/scripts # scripts
    environment:
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:bazarr
      - TP_THEME=${TP_THEME:?err}
    post_start:
      - command: /scripts/parse_file.sh /_setup/templates/config.yaml /config/config/config.yaml
        user: root
        environment:
          - PUID=${PUID:?err}
          - PGID=${PGID:?err}
          # setup
          - API_KEY_BAZARR=${API_KEY_BAZARR:?err}
          - DOCKER_SUBNET=${MEDIA_MANAGEMENT_DOCKER_SUBNET:?err}
          - API_KEY_SONARR=${API_KEY_SONARR:?err}
          - API_KEY_RADARR=${API_KEY_RADARR:?err}
          - API_KEY_SONARR4K=${API_KEY_SONARR4K:?err}
          - API_KEY_RADARR4K=${API_KEY_RADARR4K:?err}
          - OPENSUBTITLE_PASSWORD=${OPENSUBTITLE_PASSWORD}
          - OPENSUBTITLE_USERNAME=${OPENSUBTITLE_USERNAME}
      - command: /scripts/execute_sql.sh /config/db/bazarr.db
        user: root
