services:
  # Maintainerr - Management Dashboard
  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:2.19.0
    container_name: maintainerr
    restart: unless-stopped
    networks:
      media-management:
        ipv4_address: ${MEDIA_MANAGEMENT_DOCKER_SUBNET:?err}.32
    user: ${PUID:?err}:${PGID:?err}
    ports:
      - ${PORT_UI_MAINTAINERR:?err}:6246
    volumes:
      - ${APPS_FOLDER:?err}/maintainerr:/opt/data # config
      - ${APPS_FOLDER:?err}/maintainerr/_setup:/_setup # setup
      - ${SCRIPTS_FOLDER:?err}:/scripts # scripts
    environment:
      - TZ=${TIMEZONE:?err}
      # setup
      - API_KEY_MAINTAINERR=${API_KEY_MAINTAINERR:?err}
      - DOCKER_SUBNET=${MEDIA_MANAGEMENT_DOCKER_SUBNET:?err}
      - MS_HOST_IP=${MEDIA_SERVER_IP:?err}
      - PORT_UI_OVERSEERR=${PORT_UI_OVERSEERR:?err}
      - API_KEY_OVERSEERR=${API_KEY_OVERSEERR:?err}
      - PORT_UI_PLEX=${PORT_UI_PLEX:?err}
      - PLEX_CLAIM=${PLEX_CLAIM:?err}
      - PORT_UI_RADARR=${PORT_UI_RADARR:?err}
      - API_KEY_RADARR=${API_KEY_RADARR:?err}
      - PORT_UI_RADARR4K=${PORT_UI_RADARR4K:?err}
      - API_KEY_RADARR4K=${API_KEY_RADARR4K:?err}
      - PORT_UI_SONARR=${PORT_UI_SONARR:?err}
      - API_KEY_SONARR=${API_KEY_SONARR:?err}
      - PORT_UI_SONARR4K=${PORT_UI_SONARR4K:?err}
      - API_KEY_SONARR4K=${API_KEY_SONARR4K:?err}
      - PLEX_FRIENDLY_NAME=${PLEX_FRIENDLY_NAME:?err}
      # - DEBUG=true # uncomment (remove the hashtag) to enable debug logs
    post_start:
      - command: /scripts/execute_sql.sh /opt/data/maintainerr.sqlite
        user: root
