services:
  # Prowlarr - Indexer and Search Manager
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.0.5
    container_name: prowlarr
    restart: unless-stopped
    networks:
      media-management:
        ipv4_address: ${MEDIA_MANAGEMENT_DOCKER_SUBNET:?err}.15
    user: ${PUID:?err}:${PGID:?err}
    depends_on:
      flaresolverr:
        condition: service_started
        restart: false
    ports:
      - ${PORT_UI_PROWLARR:?err}:9696
    dns:
      - 1.1.1.1
    volumes:
      - ${APPS_FOLDER:?err}/prowlarr:/config # config
      - ${APPS_FOLDER:?err}/prowlarr/_setup:/_setup # setup
      - ${SCRIPTS_FOLDER:?err}:/scripts # scripts
    environment:
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:prowlarr
      - TP_THEME=${TP_THEME:?err}
    post_start:
      - command: /scripts/parse_file.sh /_setup/templates/config.xml /config/config.xml
        user: root
        environment:
          - PUID=${PUID:?err}
          - PGID=${PGID:?err}
          # setup
          - API_KEY_PROWLARR=${API_KEY_PROWLARR:?err}
      - command: /scripts/execute_sql.sh /config/prowlarr.db
        user: root
        environment:
          # setup
          - DOCKER_SUBNET=${MEDIA_MANAGEMENT_DOCKER_SUBNET:?err}
          - API_KEY_RADARR=${API_KEY_RADARR:?err}
          - API_KEY_RADARR4K=${API_KEY_RADARR4K:?err}
          - API_KEY_SONARR=${API_KEY_SONARR:?err}
          - API_KEY_SONARR4K=${API_KEY_SONARR4K:?err}
          - PORT_SERVICE_FLARESOLVERR=${PORT_SERVICE_FLARESOLVERR:?err}
          - PORT_UI_PROWLARR=${PORT_UI_PROWLARR:?err}
          - PORT_UI_QBITTORRENT=${PORT_UI_QBITTORRENT:?err}
          - PORT_UI_RADARR=${PORT_UI_RADARR:?err}
          - PORT_UI_RADARR4K=${PORT_UI_RADARR4K:?err}
          - PORT_UI_SONARR=${PORT_UI_SONARR:?err}
          - PORT_UI_SONARR4K=${PORT_UI_SONARR4K:?err}
          - SHAREWOOD_PASSKEY=${SHAREWOOD_PASSKEY:?err}

  # Flaresolverr - Cloudflare Proxy Server 
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.2
    container_name: flaresolverr
    restart: unless-stopped
    networks:
      media-management:
        ipv4_address: ${MEDIA_MANAGEMENT_DOCKER_SUBNET:?err}.16
    ports:
      - ${PORT_SERVICE_FLARESOLVERR:?err}:8191
    dns:
      - 1.1.1.1
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TIMEZONE:?err}
