services:
  # Homarr - Application Dashboard
  homarr:
    image: ghcr.io/homarr-labs/homarr:v1.43.2
    container_name: homarr
    restart: unless-stopped
    networks:
      management:
        ipv4_address: ${MANAGEMENT_DOCKER_SUBNET:?err}.11
    ports:
      - ${PORT_UI_HOMARR:?err}:7575
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPS_FOLDER:?err}/homarr:/appdata # data
      - ${APPS_FOLDER:?err}/homarr/_setup:/_setup # setup
      - ${SCRIPTS_FOLDER:?err}:/scripts # scripts
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_ENCRYPTION_KEY:?err}
      # oidc
      - AUTH_PROVIDERS=oidc
      - AUTH_OIDC_CLIENT_ID=homarr
      - AUTH_OIDC_CLIENT_SECRET=${HOMARR_OIDC_CLIENT_SECRET:?err}
      - AUTH_OIDC_ISSUER=https://auth.${INTERNAL_DOMAIN:?err}
      - AUTH_OIDC_CLIENT_NAME=Authelia
      - AUTH_OIDC_FORCE_USERINFO=true
      - AUTH_OIDC_AUTO_LOGIN=true
    post_start:
      - command: /scripts/trust_certificate.sh "${INTERNAL_DOMAIN:?err}" "/appdata/trusted-certificates"
        user: root
      - command: /scripts/execute_sql.sh "/appdata/db/db.sqlite"
        user: root
        environment:
          - INTERNAL_DOMAIN=${INTERNAL_DOMAIN:?err}
          # - DOCKER_SUBNET=${MANAGEMENT_DOCKER_SUBNET:?err}
          # - MS_HOST_IP=${MEDIA_SERVER_IP:?err}
          # - PORT_UI_OVERSEERR=${PORT_UI_OVERSEERR:?err}
          # - API_KEY_OVERSEERR=${API_KEY_OVERSEERR:?err}
          # - PORT_UI_RADARR=${PORT_UI_RADARR:?err}
          # - API_KEY_RADARR=${API_KEY_RADARR:?err}
          # - PORT_UI_RADARR4K=${PORT_UI_RADARR4K:?err}
          # - API_KEY_RADARR4K=${API_KEY_RADARR4K:?err}
          # - PORT_UI_SONARR=${PORT_UI_SONARR:?err}
          # - API_KEY_SONARR=${API_KEY_SONARR:?err}
          # - PORT_UI_SONARR4K=${PORT_UI_SONARR4K:?err}
          # - API_KEY_SONARR4K=${API_KEY_SONARR4K:?err}
          # - API_KEY_PROWLARR=${API_KEY_PROWLARR:?err}
          # - PORT_UI_PROWLARR=${PORT_UI_PROWLARR:?err}
          # - PORT_UI_QBITTORRENT=${PORT_UI_QBITTORRENT:?err}
