services:
  # Portainer - Remote Docker container management
  portainer:
    image: portainer/portainer-ce:2.35.0-alpine
    container_name: portainer
    restart: unless-stopped
    networks:
      management:
        ipv4_address: ${MANAGEMENT_DOCKER_SUBNET:?err}.10
    command:
      - "--admin-password"
      - "${PORTAINER_ADMIN_PASSWORD_ENCRYPTED:?err}"
      - "--templates"
      - "https://raw.githubusercontent.com/portainer/templates/master/templates-2.0.json"
    ports:
      - "${PORT_UI_PORTAINER:?err}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPS_FOLDER:?err}/portainer:/data
      - ${APPS_FOLDER:?err}/portainer/_setup:/_setup # setup
      - ${SCRIPTS_FOLDER:?err}:/scripts # scripts
    environment:
      - LOG_LEVEL=info
    post_start:
      - command: /scripts/trust_certificate.sh "${INTERNAL_DOMAIN:?err}"
        user: root
      - command: /_setup/bash/init.sh
        user: root
        environment:
          - INTERNAL_DOMAIN=${INTERNAL_DOMAIN:?err}
          - PORTAINER_OIDC_CLIENT_SECRET=${PORTAINER_OIDC_CLIENT_SECRET:?err}
          - PORTAINER_ADMIN_PASSWORD=${PORTAINER_ADMIN_PASSWORD:?err}
          # IPs
          - CLD_IP=${CLOUD_IP:?err}
          - DNS_IP=${DNS_IP:?err}
          - HA_IP=${HOME_AUTOMATION_IP:?err}
          - IM_IP=${IMMICH_IP:?err}
          - MM_IP=${MEDIA_MANAGEMENT_IP:?err}
          - MS_IP=${MEDIA_SERVER_IP:?err}
          - NTS_IP=${NOTES_IP:?err}
          - RP_IP=${REVERSE_PROXY_IP:?err}
          - SBX_IP=${SANDBOX_IP:?err}
          - VLT_IP=${VAULT_IP:?err}
          - VPN_IP=${VPN_IP:?err}
          - VSC_IP=${VSCODE_SERVER_IP:?err}
          - WB_IP=${WHITEBOARD_IP:?err}

