- name: 'Pre-task: Install python for ansible'
  hosts: all
  gather_facts: no
  tasks:
    - name: Install python3 (required for Ansible modules)
      ansible.builtin.raw: apk add --no-cache python3 py3-pip

- name: Final configuration (keymaps...)
  hosts: all
  gather_facts: yes
  vars:
    keyboard_layout: "{{ lookup('env', 'KEYBOARD_LAYOUT') | default('fr fr', true) }}"
  tasks:
    - name: Set FR keymap
      ansible.builtin.command: setup-keymap {{ keyboard_layout }}
      register: setup_keymap
      changed_when: "'Setting keymap' in setup_keymap.stdout"
      failed_when: setup_keymap.rc != 0

- name: Install base packages (git, curl, wget..) and setup docker
  hosts: all
  gather_facts: yes
  tasks:
    - name: Update package index
      ansible.builtin.package:
        update_cache: yes
    - name: Install useful packages
      ansible.builtin.package:
        name:
          - ca-certificates
          - gnupg
          - curl
          - wget
          - vim
        state: present
    
    - name: Install networking / security packages
      ansible.builtin.package:
        name:
          - nftables
        state: present
    
    - name: Install "run" packages
      ansible.builtin.package:
        name:
          - git
        state: present
    
    # Docker will be installed via cloud init only in VMs where it's needed
    # We already create the group and add the user to it for simplicity later
    # Ensure the docker group exists (before adding users)
    - name: Ensure docker group exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add admin to docker group
      ansible.builtin.user:
        name: admin
        groups: docker
        append: yes

- name: Hardening SSH config
  hosts: all
  gather_facts: yes
  tasks:
    # Enforce SSH key only, and disable ssh as root entirely
    - name: SSH - Disable root login entirely
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?\s*PermitRootLogin\s+.*$'
        line: 'PermitRootLogin no'
        create: false
        backrefs: false
      notify: Reload sshd

    - name: SSH - Disable password authentication globally (keys only)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?\s*PasswordAuthentication\s+.*$'
        line: 'PasswordAuthentication no'
        create: false
        backrefs: false
      notify: Reload sshd

    - name: SSH - Disable SSH challenge/keyboard-interactive auth
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?\s*ChallengeResponseAuthentication\s+.*$'
        line: 'ChallengeResponseAuthentication no'
        create: false
        backrefs: false
      notify: Reload sshd

    - name: SSH - Ensure PubkeyAuthentication is explicitly enabled
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?\s*PubkeyAuthentication\s+.*$'
        line: 'PubkeyAuthentication yes'
        create: false
        backrefs: false
      notify: Reload sshd

  handlers:
    - name: Reload sshd
      ansible.builtin.service:
        name: sshd
        state: reloaded
