[global]
	# Domain used for local/lan name resolution. See apps/reverse-proxy.
	INTERNAL_DOMAIN="l.ab"
	# Domain used for external name resolution (internet). See apps/reverse-proxy.
	EXTERNAL_DOMAIN="example.com"

[infra]
	## Users
	# Passwords will automatically be hashed with sha512
	# Root user
	ROOT_PASSWORD="not_implemented()"
	# Admin user (homelab)
	USER_HOMELAB_PASSWORD="not_implemented()"

	## Networking
	# IP of local PC that runs IAC
	IP_CONTROL_NODE="192.168.1.165"
	# Server IPs
	IP_SERVER="192.168.1.200"
	IP_GATEWAY="192.168.1.254"
	IP_NAMESERVER="192.168.1.254"

[users]
	# Is overriden by the users-config.toml file if defined
	
	# Mandatory "admin" user password used accross apps and SSO Provider
	ADMIN_PASSWORD="not_implemented()"
	# Optional
	# JSON array of user objects:
	#   [{"name":"user","password":"password","group":"family"}, ...]
	USERS="[]"

[iac] # iac
	## Proxmox setup
	# Admin user in proxmox UI (for Proxmox VE Auth server)
	PROXMOX_ADMIN_PASSWORD="not_implemented()" # Must be longer than 8 char
	
	# For automation
	PROXMOX_PACKER_PASSWORD="generate_password(20)"  # Must be longer than 8 char
	PROXMOX_TERRAFORM_PASSWORD="generate_password(20)"  # Must be longer than 8 char
	PROXMOX_TEMPLATE_ROOT_PASSWORD="generate_password(20)"

	# VM keyboard layout 
	# - french/azerty: "fr fr" (default)
	# - us/qwerty: "us us"
	KEYBOARD_LAYOUT="fr fr"

[preseed] # preseed
	# /dev/sda for SSD ; /dev/nvme0n1 for NVME
	DISK="/dev/sda"

	# Proxmox host keyboard layout
	# - french/azerty: "fr(azery)" (default) (not a typo)
	# - us/qwerty: "us"
	KEYBOARD_LAYOUT="fr(azery)"

[cloud] # apps/cloud
	enabled=false

	NEXTCLOUD_ADMIN_USER=""
	NEXTCLOUD_ADMIN_PASSWORD=""
	MYSQL_USER=""
	MYSQL_PASSWORD=""

[dns] # apps/dns
	enabled=true

[firewall-gw] # apps/firewall-gw
	enabled=true

[firewall-mgmt] # apps/firewall-mgmt
	enabled=true

[firewall-srv] # apps/firewall-srv
	enabled=true

[home-automation] # apps/home-automation
	enabled=false

[immich] # apps/immich
	enabled=false

	DB_PASSWORD=""

[jump] # apps/jump
	enabled=true

[management] # apps/management
	enabled=true

	## Portainer
	# Authelia OIDC client secret
	PORTAINER_OIDC_CLIENT_SECRET="generate_token(64)"
	
	## Homarr
	HOMARR_SECRET_ENCRYPTION_KEY="generate_token(32)"
	# Authelia OIDC client secret
	HOMARR_OIDC_CLIENT_SECRET="generate_token(64)"

[media-management] # apps/media-management
	enabled=true

	## Gluetun (vpn)
	# VPN provider credentials. Example: nordvpn, protonvpn
	# https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers
	VPN_SERVICE_PROVIDER="protonvpn"
	VPN_USERNAME="not_implemented()"
	VPN_PASSWORD="not_implemented()"

	## Arr
	# Provide any value you want that will be used as API key
	# Generator:  https://it-tools.tech/token-generator
	API_KEY_PROWLARR="generate_token(64)"
	API_KEY_BAZARR="generate_token(64)"
	API_KEY_RADARR="generate_token(64)"
	API_KEY_RADARR4K="generate_token(64)"
	API_KEY_SONARR="generate_token(64)"
	API_KEY_SONARR4K="generate_token(64)"
	API_KEY_MAINTAINERR="generate_token(64)"

	## Bazarr
	# Optional: For automatic subtitles with Bazarr
	# Create an account here: https://www.opensubtitles.com/
	OPENSUBTITLE_USERNAME=""
	OPENSUBTITLE_PASSWORD=""

	## Prowlarr
	# Private providers
	# Optional: Sharewood indexer passkey
	SHAREWOOD_PASSKEY=""

[media-server] # apps/media-server
	enabled=true

	## Plex
	# Token for the Plex server. It is generated the first time, when the server is claimed.
	PLEX_CLAIM=""
	# Id of the machine for your Plex server. It is generated the first time, when the server is claimed.
	PLEX_MACHINE_IDENTIFIER=""
	# Username and Email for the account linked with the Plex server.
	PLEX_USERNAME=""
	PLEX_EMAIL=""
	PLEX_FRIENDLY_NAME="media-server"

	## Seerr
	# Provide any value you want that will be used as API key
	# Generator: https://it-tools.tech/token-generator
	API_KEY_OVERSEERR="generate_token(64)"

[nas] # apps/nas
	enabled=true

[notes] # apps/notes
	enabled=false

[reverse-proxy] # apps/reverse-proxy
	enabled=true

	## Swag
	# Which DNS provider you are using
	# Depending on the DNS provider, you need to add support for the correct .ini file in apps/reverse-proxy/apps/swag/dns-conf
	# Already handled automatically: cloudflare, duckdns
	# See the doc in apps/reverse-proxy/apps/swag/dns-conf
	DNS_PROVIDER="cloudflare"
	# The token for your DNS provider (see apps/reverse-proxy/apps/swag/dns-conf)
	DNS_PROVIDER_TOKEN="not_implemented()"
    # DNS Propagation time (in second)
	DNS_PROPAGATION_TIME=30

	## Authelia
	# Provide any value you want that will be used as API key
	# Generator:  https://it-tools.tech/token-generator
	# The secret key used to sign and verify the JWT.
	AUTHELIA_JWT_SECRET="generate_token(64)"
	# The encryption key that is used to encrypt sensitive information in the database. 
	AUTHELIA_ENCRYPTION_KEY="generate_token(32)" # Min length: 20
	# OIDC secret
	AUTHELIA_OIDC_HMAC_SECRET="generate_token(32)"
	# OIDC JWKS key (RSA PEM)
	# Base64 encoded RSA private key
	# openssl genrsa -traditional 4096 2>/dev/null | base64 -w0
	AUTHELIA_OIDC_JWKS_KEY="generate_rsa()"

	## DDNS
	# Optional: For cloudflare only
	# On the homepage, on the account home, on the domain line, click "copy zone ID" (clickable dots at the right of the line)
	CLOUDFLARE_ZONE_ID=""

[sandbox] # apps/sandbox
	enabled=true

[vault] # apps/vault
	enabled=false

	VAULTWARDEN_ADMIN_TOKEN=""

[vpn] # apps/vpn
	enabled=true

[vscode-server] # apps/vscode-server
	enabled=false

	VSCODE_SERVER_PASSWORD=""

[whiteboard] # apps/whiteboard
	enabled=false
