[global]
	# Domain used for local/lan name resolution. See apps/reverse-proxy.
	INTERNAL_DOMAIN="l.ab"
	# Domain used for external name resolution (internet). See apps/reverse-proxy.
	EXTERNAL_DOMAIN="example.com"

[infra]
	# IP of local PC that runs IAC
	IP_CONTROL_NODE="192.168.1.165"
	# Server IPs
	IP_GATEWAY="192.168.1.254"
	IP_NAMESERVER="192.168.1.254"
	IP_SERVER="192.168.1.200"

[iac]
	# Proxmox setup
	PROXMOX_ADMIN_PASSWORD="long_password1!" # Must be longer than 8 char
	PROXMOX_PACKER_PASSWORD="long_packer_password1!"  # Must be longer than 8 char
	PROXMOX_TERRAFORM_PASSWORD="long_terraform_password1!"  # Must be longer than 8 char
	PROXMOX_TEMPLATE_ROOT_PASSWORD="long_template_password1!"

[preseed] # preseed
	# /dev/sda for SSH ; /dev/nvme0n1 for NVME
	DISK="/dev/sda"
	# Passwords will automatically be hashed with sha512
	# Root user
	ROOT_PASSWORD="long_root_password1!"
	# Admin user (homelab)
	USER_HOMELAB_PASSWORD="long_password1!"

[cloud] # apps/cloud
	enabled=false

	NEXTCLOUD_ADMIN_USER=""
	NEXTCLOUD_ADMIN_PASSWORD=""
	MYSQL_USER=""
	MYSQL_PASSWORD=""

[dns]
	enabled=true

[firewall-gw]
	enabled=true

[firewall-mgmt]
	enabled=true

[firewall-srv]
	enabled=true

[home-automation]
	enabled=false

[immich] # apps/immich
	enabled=false

	DB_PASSWORD=""

[jump]
	enabled=true

[media-management] # apps/media-management
	enabled=true

	# VPN provider credentials. Example: nordvpn, protonvpn
	# https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers
	VPN_SERVICE_PROVIDER="protonvpn"
	VPN_USERNAME=""
	VPN_PASSWORD=""

	# Provide any value you want that will be used as API key
	# Generator:  https://it-tools.tech/token-generator
	API_KEY_PROWLARR=""
	API_KEY_BAZARR=""
	API_KEY_RADARR=""
	API_KEY_RADARR4K=""
	API_KEY_SONARR=""
	API_KEY_SONARR4K=""
	API_KEY_MAINTAINERR=""

	# For automatic subtitles with Bazarr
	# Create an account here: https://www.opensubtitles.com/
	OPENSUBTITLE_USERNAME=""
	OPENSUBTITLE_PASSWORD=""

	# Sharewood indexer passkey
	SHAREWOOD_PASSKEY=""

[media-server] # apps/media-server
	enabled=true

	# Token for the Plex server. It is generated the first time, when the server is claimed.
	PLEX_CLAIM=""
	# Id of the machine for your Plex server. It is generated the first time, when the server is claimed.
	PLEX_MACHINE_IDENTIFIER=""
	# Username and Email for the account linked with the Plex server.
	PLEX_USERNAME=""
	PLEX_EMAIL=""
	PLEX_FRIENDLY_NAME="media-server"

	# Provide any value you want that will be used as API key
	# Generator: https://it-tools.tech/token-generator
	API_KEY_OVERSEERR=""

[nas]
	enabled=true

[notes]
	enabled=false

[reverse-proxy] # apps/reverse-proxy
	enabled=true

	# Which DNS provider you are using
	# Depending on the DNS provider, you need to add support for the correct .ini file in apps/reverse-proxy/apps/swag/dns-conf
	# Already handled automatically: cloudflare, duckdns
	# See the doc in apps/reverse-proxy/apps/swag/dns-conf
	DNS_PROVIDER="cloudflare"
	# The token for your DNS provider (see apps/reverse-proxy/apps/swag/dns-conf)
	DNS_PROVIDER_TOKEN=""
    # DNS Propagation time (in second)
	DNS_PROPAGATION_TIME=30

	# The secret key used to sign and verify the JWT.
	# Any token you want.
	AUTHELIA_JWT_SECRET="a_very_important_secret"
	# The encryption key that is used to encrypt sensitive information in the database. 
	# Any token you want. Min length: 20
	AUTHELIA_ENCRYPTION_KEY="you_must_generate_a_random_string_of_more_than_twenty_chars"
	# The user used to authenticate to Authelia
	AUTHELIA_USER_NAME="admin"
	AUTHELIA_USER_EMAIL="admin@gmail.com"
	# Password will automatically be hashed with argon2
	AUTHELIA_USER_PASSWORD="long_password1!"
	AUTHELIA_USER_FAMILY_PASSWORD="long_password2!"

	# DDNS
	# For cloudflare only
	# On the homepage, on the account home, on the domain line, click "copy zone ID" (clickable dots at the right of the line)
	CLOUDFLARE_ZONE_ID=""

[sandbox]
	enabled=false

[todo]
	enabled=false

[vault] # apps/vault
	enabled=false

	VAULTWARDEN_ADMIN_TOKEN=""

[vpn]
	enabled=true

[vscode-server] # apps/vscode-server
	enabled=false

	VSCODE_SERVER_PASSWORD=""

[whiteboard]
	enabled=false
