flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0; 
		policy drop;

		iifname lo accept
		ct state established,related accept
		ct state invalid drop
		
		# Allow ping and other ICMP control (v4/v6)
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# Allow SSH (22/tcp) from mgmt
		ip saddr 10.10.31.9 tcp dport 22 accept # from mgmt (jump)
		tcp dport 22 drop # from everyone

		# Allow Portainer (19001/tcp) from mgmt
		ip saddr 10.10.31.9 tcp dport 19001 accept # from mgmt (management)
		tcp dport 19001 drop # from everyone

		# Allow all ports from dmz (RP) and intern
		ip saddr 10.10.31.10 accept # from reverse proxy
		ip saddr 10.10.32.0/24 accept # from intern

		# Allow Plex local network discovery from LAN
		ip saddr 192.168.1.0/24 tcp dport 32400 accept
		ip saddr 192.168.1.0/24 udp dport 32410-32414 accept

		# Allow Jellyfin local network discovery from LAN
		ip saddr 192.168.1.0/24 tcp dport 8096 accept
		ip saddr 192.168.1.0/24 udp dport 7359 accept
	}

	chain forward {
		type filter hook forward priority 0; 
		policy drop;
		
		# Forward Docker
		ip saddr 172.17.0.0/12 accept
       	ip daddr 172.17.0.0/12 accept
	}

	chain output {
		type filter hook output priority 0; 
		policy accept;
	}
}
