kernel: virt
specs:
  cores: 1
  ram_size: 1024 # MB
  disk_size: 6 # GB
  additional_disks: []
  pci_devices: []
order_tier: 2
config:
  docker: false
  router: false
  routes:
    - network: 10.10.1.0/24 # gw
      via: 10.10.2.2 # firewall-mgmt
    - network: 10.10.30.0/24 # dmz
      via: 10.10.2.2 # firewall-mgmt
    - network: 10.10.31.0/24 # extern
      via: 10.10.2.2 # firewall-mgmt
    - network: 10.10.32.0/24 # intern
      via: 10.10.2.2 # firewall-mgmt
    - network: 10.10.33.0/24 # jail
      via: 10.10.2.2 # firewall-mgmt
    - network: 10.10.4.0/24 # bpn
      via: 10.10.2.2 # firewall-mgmt
  dns_servers: [1.1.1.1, 8.8.8.8]
nics:
  - bridge: vmbr2 # mgmt
    ipv4: 10.10.2.10/24
    gateway: 10.10.2.1
nas: null
