server {
	listen 443 ssl;
	listen [::]:443 ssl;

	# Enable 5000 port for internal traffic
	# This allows filtering for internal traffic at the router level
	listen 5000 ssl;
	listen [::]:5000 ssl;

	server_name authelia.${INTERNAL_DOMAIN} auth.${INTERNAL_DOMAIN};

	include /config/nginx/htaccess.conf;

	include /config/nginx/ssl-private.conf;

	client_max_body_size 0;

	location / {
		include /config/nginx/proxy.conf;
		include /config/nginx/resolver.conf;
		set $upstream_app authelia;
		set $upstream_port ${PORT_UI_AUTHELIA};
		set $upstream_proto http;
		proxy_pass $upstream_proto://$upstream_app:$upstream_port;
	}

	location ~ (/authelia)?/api {
		include /config/nginx/proxy.conf;
		include /config/nginx/resolver.conf;
		set $upstream_app authelia;
		set $upstream_port ${PORT_UI_AUTHELIA};
		set $upstream_proto http;
		proxy_pass $upstream_proto://$upstream_app:$upstream_port;
	}
}
