server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name ddns-updater.${INTERNAL_DOMAIN} ddns.${INTERNAL_DOMAIN};

	include /config/nginx/ssl-private.conf;

	client_max_body_size 0;

	# enable for Authelia (requires authelia-location.conf in the location block)
	include /config/authelia/authelia-server.conf;

	location / {
		# enable for Authelia (requires authelia-server.conf in the server block)
		include /config/authelia/authelia-location.conf;

		include /config/nginx/proxy.conf;
		include /config/nginx/resolver.conf;
		set $upstream_app ddns-updater;
		set $upstream_port 8000;
		set $upstream_proto http;
		proxy_pass $upstream_proto://$upstream_app:$upstream_port;
	}

	location ~ (/ddns-updater)?/api {
		include /config/nginx/proxy.conf;
		include /config/nginx/resolver.conf;
		set $upstream_app ddns-updater;
		set $upstream_port 8000;
		set $upstream_proto http;
		proxy_pass $upstream_proto://$upstream_app:$upstream_port;
	}
}
