server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name yamtrack.${INTERNAL_DOMAIN} tracker.${INTERNAL_DOMAIN};

	include /config/nginx/htaccess.conf;

	include /config/nginx/ssl-private.conf;

	client_max_body_size 0;

	location / {
		include /config/nginx/proxy.conf;
		include /config/nginx/resolver.conf;
		set $upstream_app ms.srv.${INTERNAL_DOMAIN};
		set $upstream_port ${PORT_UI_YAMTRACK};
		set $upstream_proto http;
		proxy_pass $upstream_proto://$upstream_app:$upstream_port;
	}
}
