specs:
  cores: 2
  ram_size: 2048 # MB
  disk_size: 10 # GB
  additional_disks: []
  pci_devices: []
config:
  docker: true
  router: false
  routes: []
  dns_servers: [1.1.1.1, 8.8.8.8]
order_tier: 100
nics:
  - bridge: vmbr3 # srv
    trunks: 
      - id: 30 # dmz
        ipv4: 10.10.30.2/24
        gateway: 10.10.30.1
      - id: 31 # extern
        ipv4: 10.10.31.2/24
      - id: 32 # intern
        ipv4: 10.10.32.2/24
nas: null
