kernel: virt
specs:
  cores: 1
  ram_size: 2048 # MB
  disk_size: 10 # GB
  additional_disks: []
  pci_devices: []
order_tier: 2
config:
  docker: true
  router: false
  routes: []
  dns_servers: [1.1.1.1, 8.8.8.8]
nics:
  - bridge: vmbr4 # vpn
    ipv4: 10.10.4.10/24
    gateway: 10.10.4.1
nas: null
