flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0;
		policy drop;

		# Established/related connections
		ct state established,related accept
		ct state invalid drop

		# Allow loopback
		iifname "lo" accept

		# Allow ping
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# Allow SSH (22/tcp) from mgmt
		ip saddr 10.10.1.9 tcp dport 22 accept # from mgmt
	}

	chain forward {
		type filter hook forward priority 0;
		policy drop;

		ct state established,related accept

		# Allow forwarded traffic to RP (443) and JMP (22 via 2222 DNAT)
		ip saddr != 10.10.0.0/16 ip daddr 10.10.30.10 tcp dport 443 accept
		ip saddr 192.168.1.0/24 ip daddr 10.10.2.10 tcp dport 22 accept

		# Allow forwarded traffic to DNS (10.10.1.200)
		ip daddr 10.10.1.200 udp dport 53 accept
		ip daddr 10.10.1.200 tcp dport 53 accept

		## == Additional ports / app specifics ==
		# Allow forwarded traffic to Plex (10.10.31.11) - only from LAN
		ip saddr 192.168.1.0/24 ip daddr 10.10.31.11 tcp dport 32400 accept
		ip saddr 192.168.1.0/24 ip daddr 10.10.31.11 udp dport 32410-32414 accept
		# Allow forwarded traffic to Jellyfin (10.10.31.11) - only from LAN
		ip saddr 192.168.1.0/24 ip daddr 10.10.31.11 tcp dport 8096 accept
		ip saddr 192.168.1.0/24 ip daddr 10.10.31.11 udp dport 7359 accept
		# Allow forwarded traffic to NAS (10.10.32.30) - only from LAN
		ip saddr 192.168.1.0/24 ip daddr 10.10.32.30 tcp dport 2049 accept # NFS
		ip saddr 192.168.1.0/24 ip daddr 10.10.32.30 tcp dport 445 accept # SAMBA NFS
		## == Additional ports / app specifics ==

		# Allow VMs to go out to Internet (their replies will match established,related)
		ip saddr {10.10.1.0/24, 10.10.2.0/24, 10.10.30.0/24, 10.10.31.0/24, 10.10.32.0/24} oifname "eth0" accept
	}

	chain output {
		type filter hook output priority 0;
		policy accept;
	}
}

table ip nat {
	chain prerouting {
		type nat hook prerouting priority -100;
		policy accept;

		# DNAT: 443 -> RP
		ip saddr != 10.10.0.0/16 tcp dport 443 dnat to 10.10.30.10:443

		# DNAT: 2222 -> JMP:22
		ip saddr 192.168.1.0/24 tcp dport 2222 dnat to 10.10.2.10:22

		## == Additional ports / app specifics ==
		# DNAT: Plex ports -> Plex server (10.10.31.11) - only from LAN
		ip saddr 192.168.1.0/24 tcp dport 32400 dnat to 10.10.31.11:32400
		ip saddr 192.168.1.0/24 udp dport 32410-32414 dnat to 10.10.31.11
		# DNAT: NAS ports -> NAS server (10.10.32.30) - only from LAN
		ip saddr 192.168.1.0/24 tcp dport 2049 dnat to 10.10.32.30:2049 # NFS
		ip saddr 192.168.1.0/24 tcp dport 445 dnat to 10.10.32.30:445 # SAMBA NFS
		## == Additional ports / app specifics ==
	}

	chain postrouting {
		type nat hook postrouting priority 100;
		policy accept;

		# Masquerade outbound for subnets
		# DMZ
		ip saddr 10.10.30.0/24 ip daddr != 10.10.1.200 oifname "eth0" masquerade
		# EXTERN
		ip saddr 10.10.31.0/24 ip daddr != 10.10.1.200 oifname "eth0" masquerade
		# INTERN
		ip saddr 10.10.32.0/24 ip daddr != 10.10.1.200 oifname "eth0" masquerade
		# MGMT
		ip saddr 10.10.2.0/24  ip daddr != 10.10.1.200 oifname "eth0" masquerade
	}
}
