flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0;
		policy drop;

		# Established/related connections
		ct state established,related accept
		ct state invalid drop

		# Allow loopback
		iifname "lo" accept

		# Allow ping
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# Allow SSH (22/tcp) from mgmt
		ip saddr 10.10.1.9 tcp dport 22 accept # from mgmt
	}

	chain forward {
		type filter hook forward priority 0;
		policy drop;

		ct state established,related accept

		# Allow forwarded traffic to RP (443) and JMP (22 via 2222 DNAT)
		ip saddr != 10.10.0.0/16 ip daddr 10.10.30.2 tcp dport 443 accept
		ip saddr 192.168.1.0/24 ip daddr 10.10.2.11 tcp dport 22 accept

		# Allow forwarded traffic to DNS (10.10.1.200)
		ip daddr 10.10.1.200 udp dport 53 accept
		ip daddr 10.10.1.200 tcp dport 53 accept

		# Allow VMs to go out to Internet (their replies will match established,related)
		ip saddr {10.10.30.0/24, 10.10.31.0/24, 10.10.32.0/24, 10.10.2.0/24} oifname "eth0" accept
	}

	chain output {
		type filter hook output priority 0;
		policy accept;
	}
}

table ip nat {
	chain prerouting {
		type nat hook prerouting priority -100;
		policy accept;

		# DNAT: 443 -> RP
		ip saddr != 10.10.0.0/16 tcp dport 443 dnat to 10.10.30.2:443

		# DNAT: 2222 -> JMP:22
		ip saddr 192.168.1.0/24 tcp dport 2222 dnat to 10.10.2.11:22
	}

	chain postrouting {
		type nat hook postrouting priority 100;
		policy accept;

		# Masquerade outbound for subnets
		ip saddr 10.10.30.0/24 oifname "eth0" masquerade
		ip saddr 10.10.31.0/24 oifname "eth0" masquerade
		ip saddr 10.10.32.0/24 oifname "eth0" masquerade
		ip saddr 10.10.2.0/24  oifname "eth0" masquerade
	}
}
