flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0; 
		policy drop;

		iifname lo accept
		ct state established,related accept
		ct state invalid drop

		# Allow ping and other ICMP control (v4/v6)
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# Allow SSH to this host from mgmt (jump)
		ip saddr 10.10.2.10 tcp dport 22 accept
	}

	chain forward {
		type filter hook forward priority 0; 
		policy drop;

		# Allow replies for forwarded flows
		ct state established,related accept

		# Forward SSH (22/tcp) from mgmt (jump) to internal subnets
		ip saddr 10.10.2.10 ip daddr 10.10.1.0/24  tcp dport 22 accept # gw
		ip saddr 10.10.2.10 ip daddr 10.10.30.0/24 tcp dport 22 accept # dmz
		ip saddr 10.10.2.10 ip daddr 10.10.31.0/24 tcp dport 22 accept # extern
		ip saddr 10.10.2.10 ip daddr 10.10.32.0/24 tcp dport 22 accept # intern
		
		# Forward portainer (19001/tcp) from mgmt (management) to internal subnets
		ip saddr 10.10.2.11 ip daddr 10.10.1.0/24  tcp dport 19001 accept # gw
		ip saddr 10.10.2.11 ip daddr 10.10.30.0/24 tcp dport 19001 accept # dmz
		ip saddr 10.10.2.11 ip daddr 10.10.31.0/24 tcp dport 19001 accept # extern
		ip saddr 10.10.2.11 ip daddr 10.10.32.0/24 tcp dport 19001 accept # intern
	}

	chain output {
		type filter hook output priority 0; 
		policy accept;
	}
}

table ip nat {
	chain postrouting {
		type nat hook postrouting priority 100;
		policy accept;

		# Masquerade jump to internal subnets
		ip saddr 10.10.2.10 ip daddr 10.10.1.0/24  masquerade # gw
		ip saddr 10.10.2.10 ip daddr 10.10.30.0/24 masquerade # dmz
		ip saddr 10.10.2.10 ip daddr 10.10.31.0/24 masquerade # extern
		ip saddr 10.10.2.10 ip daddr 10.10.32.0/24 masquerade # intern
		
		# Masquerade management to internal subnets
		ip saddr 10.10.2.11 ip daddr 10.10.1.0/24  masquerade # gw
		ip saddr 10.10.2.11 ip daddr 10.10.30.0/24 masquerade # dmz
		ip saddr 10.10.2.11 ip daddr 10.10.31.0/24 masquerade # extern
		ip saddr 10.10.2.11 ip daddr 10.10.32.0/24 masquerade # intern
	}
}
