flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0; 
		policy drop;

		iifname lo accept
		ct state established,related accept
		ct state invalid drop

		# Allow ping and other ICMP control (v4/v6)
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# Allow SSH to this host from mgmt (jump)
		ip saddr 10.10.2.10 tcp dport 22 accept
		tcp dport 22 drop # from everyone
	}

	chain forward {
		type filter hook forward priority 0; 
		policy drop;

		# Allow replies for forwarded flows
		ct state established,related accept

		# Forward SSH (22/tcp) from mgmt (jump) to internal subnets
		ip saddr 10.10.2.10 ip daddr 10.10.1.0/24  tcp dport 22 accept # gw
		ip saddr 10.10.2.10 ip daddr 10.10.30.0/24 tcp dport 22 accept # dmz
		ip saddr 10.10.2.10 ip daddr 10.10.31.0/24 tcp dport 22 accept # extern
		ip saddr 10.10.2.10 ip daddr 10.10.32.0/24 tcp dport 22 accept # intern
		ip saddr 10.10.2.10 ip daddr 10.10.33.0/24 tcp dport 22 accept # jail
		ip saddr 10.10.2.10 ip daddr 10.10.4.0/24 tcp dport 22 accept # vpn
		
		# Forward portainer (19001/tcp) from mgmt (management) to internal subnets
		ip saddr 10.10.2.11 ip daddr 10.10.1.0/24  tcp dport 19001 accept # gw
		ip saddr 10.10.2.11 ip daddr 10.10.30.0/24 tcp dport 19001 accept # dmz
		ip saddr 10.10.2.11 ip daddr 10.10.31.0/24 tcp dport 19001 accept # extern
		ip saddr 10.10.2.11 ip daddr 10.10.32.0/24 tcp dport 19001 accept # intern
		ip saddr 10.10.2.11 ip daddr 10.10.4.0/24 tcp dport 19001 accept # vpn
		
		# Forward RP -> mgmt (management)
		# portainer (9443/tcp)
		ip saddr 10.10.30.10 ip daddr 10.10.2.11/24 tcp dport 9443 accept # mgmt
		# homarr (7575/tcp)
		ip saddr 10.10.30.10 ip daddr 10.10.2.11/24 tcp dport 7575 accept # mgmt
		
		# Forward "regular traffic" (non management)
		# Forward DNS (53/tcp, 53/udp) to gw (dns)
		ip daddr 10.10.1.200 udp dport 53 accept # gw - dns
		ip daddr 10.10.1.200 tcp dport 53 accept # gw - dns
		# Forward 5000 (https internal) from mgmt (management) to gw (firewall-gw)
		ip saddr 10.10.2.11 ip daddr 10.10.30.10 tcp dport 5000 accept # dmz - rp
	}

	chain output {
		type filter hook output priority 0; 
		policy accept;
	}
}

table ip nat {
	chain prerouting {
		type nat hook prerouting priority -100;
		policy accept;

		# DNAT: internal:443 -> RP:5000
		# Rewrite internal 443 traffic to reverse proxy to 5000
		ip saddr 10.10.2.0/24 ip daddr 10.10.30.10 tcp dport 443 dnat to 10.10.30.10:5000
	}

	chain postrouting {
		type nat hook postrouting priority 100;
		policy accept;

		# Masquerade jump to internal subnets
		ip saddr 10.10.2.10 ip daddr 10.10.1.0/24  masquerade # gw
		ip saddr 10.10.2.10 ip daddr 10.10.30.0/24 masquerade # dmz
		ip saddr 10.10.2.10 ip daddr 10.10.31.0/24 masquerade # extern
		ip saddr 10.10.2.10 ip daddr 10.10.32.0/24 masquerade # intern
		ip saddr 10.10.2.10 ip daddr 10.10.33.0/24 masquerade # jail
		ip saddr 10.10.2.10 ip daddr 10.10.4.0/24 masquerade # vpn
		
		# Masquerade management to internal subnets
		ip saddr 10.10.2.11 ip daddr 10.10.1.0/24  masquerade # gw
		ip saddr 10.10.2.11 ip daddr 10.10.30.0/24 masquerade # dmz
		ip saddr 10.10.2.11 ip daddr 10.10.31.0/24 masquerade # extern
		ip saddr 10.10.2.11 ip daddr 10.10.32.0/24 masquerade # intern
		ip saddr 10.10.2.11 ip daddr 10.10.4.0/24 masquerade # vpn
	}
}
