specs:
  cores: 1
  memory_size: 2048 # MB
  disk_size: 10 # GB
config:
  docker: false
  router: true
  routes: []
order: 2
dns_servers: [1.1.1.1, 8.8.8.8]
nics:
  - bridge: vmbr2 # mgmt
    ipv4: 10.10.2.2/24
    gateway: 10.10.2.1
  - bridge: vmbr1 # gw
    ipv4: 10.10.1.9/24
  - bridge: vmbr3 # srv
    trunks: 
      - id: 30 # dmz
        ipv4: 10.10.30.9/24
      - id: 31 # extern
        ipv4: 10.10.31.9/24
      - id: 32 # intern
        ipv4: 10.10.32.9/24
