[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs
InstanceName=qBittorrent

[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AddTorrentStopped=false
Session\AlternativeGlobalDLSpeedLimit=0
Session\AlternativeGlobalUPSpeedLimit=0
Session\BTProtocol=TCP
Session\BandwidthSchedulerEnabled=true
Session\DefaultSavePath=/data/complete
Session\DisableAutoTMMByDefault=false
Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false
Session\ExcludedFileNames=
Session\GlobalDLSpeedLimit=200000
Session\GlobalUPSpeedLimit=200000
Session\Port=6881
Session\Preallocation=true
Session\QueueingSystemEnabled=true
Session\SSL\Port=12621
Session\ShareLimitAction=Stop
Session\TempPath=/data/incomplete
Session\TempPathEnabled=true
Session\UseAlternativeGlobalSpeedLimit=false

[Core]
AutoDeleteAddedTorrentFile=IfAdded

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
General\Locale=en
MailNotification\req_auth=true
Scheduler\end_time=@Variant(\0\0\0\xf\x1I\x97\0)
Scheduler\start_time=@Variant(\0\0\0\xf\0m\xdd\0)
WebUI\Address=*
WebUI\AlternativeUIEnabled=false
WebUI\AuthSubnetWhitelist=127.0.0.1/32, 192.168.0.0/16, 172.16.0.0/12, 10.10.0.0/16
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(OnwGEnvruxw13bVP9zSU2A==:iBTHRGRl+AnDUV9Pywr9PvU+TNx/NmhmKKrUpfNhuwIivJYk60EFKE8QR0qp0RtdvS4JSE59/9L8Fjs2duf+YQ==)"
WebUI\Port=8200
WebUI\RootFolder=
WebUI\ServerDomains=*
WebUI\SessionTimeout=3600

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
