### [!] GLOBAL
INTERNAL_DOMAIN="${INTERNAL_DOMAIN}"
EXTERNAL_DOMAIN="${EXTERNAL_DOMAIN}"
HOST_LAN_IP="${infra.IP_SERVER}"

MEDIA_SERVER_NAME="${MEDIA_SERVER_NAME}"

### [!] PLEX
# PLEX_CLAIM="${PLEX_CLAIM}"
# PLEX_USERNAME="${PLEX_USERNAME}"
# PLEX_EMAIL="${PLEX_EMAIL}"
# PLEX_MACHINE_IDENTIFIER="${PLEX_MACHINE_IDENTIFIER}"

### [!] JELLYFIN
JELLYFIN_ADMIN_PASSWORD='${users.ADMIN_PASSWORD}'

### [!] API KEY SEEDS
API_KEY_SEERR="${API_KEY_SEERR}"

### [!] MEDIA_MANAGEMENT
API_KEY_RADARR="${media-management.API_KEY_RADARR}"
API_KEY_RADARR4K="${media-management.API_KEY_RADARR4K}"
API_KEY_SONARR="${media-management.API_KEY_SONARR}"
API_KEY_SONARR4K="${media-management.API_KEY_SONARR4K}"
