
networks:
  nextcloud:
    name: nextcloud
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${NEXTCLOUD_DOCKER_SUBNET:?err}.0/24
        gateway: ${NEXTCLOUD_DOCKER_SUBNET:?err}.1

services:
  nextcloud:
    image: nextcloud # The image that will be used. The official nextcloud docker
    container_name: nextcloud # Just the name of the container. Help you identify it
    restart: unless-stopped # If something happens like the container crashes then we want the container to start up again
    networks:
      nextcloud:
        ipv4_address: "${NEXTCLOUD_DOCKER_SUBNET:?err}.30"
    depends_on: # Wait for the database and redis containers before starting nextcloud
      - nextclouddb 
      - redis
    ports: # If you have multiple web service on your server you need to change the port. I am directing nextcloud from port 80 to port 8081
      - "${PORT_UI_NEXTCLOUD:?err}:80"
    volumes: # These are important. This will map a file directory inside the container to a directory on your actual computer
      - ${APPS_FOLDER:?err}/nextcloud/html:/var/www/html # Map the /var/www/html directory in the container to the html folder in the same folder as the docker-compose.yml
      - ${APPS_FOLDER:?err}/nextcloud/custom_apps:/var/www/html/custom_apps # These volumes allow us to easily interact with the files in the container
      - ${APPS_FOLDER:?err}/nextcloud/config:/var/www/html/config
      - ${DATA_FOLDER:?err}/nextcloud/data:/var/www/html/data
    environment:
      - PUID=${PUID:?err} # The user ids. Most likely both should be 1000. Incorrectly setting these will led to file permission issues
      - PGID=${PGID:?err} # Set these to whatever your user is.
      - TZ=${TZ:?err} # Set this to your timezone
      - MYSQL_DATABASE=nextcloud # This is the database information we will set up in the next section
      - MYSQL_USER=${MYSQL_USER:?err}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?err}
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis # The redis container to use
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:?err}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:?err}
      - APACHE_SERVER_NAME=nextcloud.local
    # command: >
    #     sh -c "docker-php-entrypoint apache2-foreground &
    #     sleep 20 &&
    #     su -s /bin/sh -c 'php occ config:system:set trusted_domains 0 --value=\"*\"' www-data"

  nextclouddb:
    image: mariadb # offical mariadb image
    container_name: nextcloud-db 
    restart: unless-stopped 
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW # I honestly cant remember. If you know why let me know.
    networks:
      nextcloud:
        ipv4_address: "${NEXTCLOUD_DOCKER_SUBNET:?err}.31"
    volumes:
      - ${APPS_FOLDER:?err}/nextclouddb:/var/lib/mysql
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TZ:?err}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MYSQL_USER:?err}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?err}
      

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ${APPS_FOLDER:?err}/redis:/data  
    networks:
      nextcloud:
        ipv4_address: "${NEXTCLOUD_DOCKER_SUBNET:?err}.32"
  