#cloud-config
network:
  version: 2
  ethernets:
    %{~ for n in nics ~}
    ${n.interface}:
      match:
        macaddress: "${n.mac}"
      set-name: ${n.interface}
      dhcp4: false
      %{~ if n.ipv4 != null ~}
      addresses:
        - ${n.ipv4}
      %{~ endif ~}
      %{~ if n.gateway != null ~}
      routes:
        - to: 0.0.0.0/0
          via: ${n.gateway}
      %{~ endif ~}
      nameservers:
        addresses:
        %{~ for s in dns ~}
          - ${s}
        %{~ endfor ~}
    %{~ endfor ~}
  %{~ if length(vlans) > 0 ~}
  vlans:
    %{~ for v in vlans ~}
    ${v.interface}.${v.id}:
      id: ${v.id}
      link: ${v.interface}
      dhcp4: false
      addresses:
        - ${v.ipv4}
      %{~ if v.gateway != null ~}
      routes:
        - to: 0.0.0.0/0
          via: ${v.gateway}
      %{~ endif ~}
      nameservers:
        addresses:
        %{~ for s in dns ~}
          - ${s}
        %{~ endfor ~}
    %{~ endfor ~}
  %{~ endif ~}
