server:
    # Listen on all interfaces
    interface: 0.0.0.0
    access-control: 0.0.0.0/0 allow  # Allow public queries by default
    verbosity: 1
    do-not-query-localhost: no

    access-control-view: ${DOCKER_SUBNET}.11/32 intra

    #
    # ==== *.homelab ===
    #
    # Define a local zone for *.homelab with unrestricted access
    
    local-zone: "${INTERNAL_DOMAIN}." redirect
    local-data: "${INTERNAL_DOMAIN}. IN A ${RP_HOST_IP}"  # IP host machine reverse proxy

view:
    name: "intra"

    #
    # ==== *.intra.homelab ===
    #
    # Define a local zone for intra.homelab with restricted access
    local-zone: "intra.${INTERNAL_DOMAIN}." static

    # local-data: "cld.intra.${INTERNAL_DOMAIN}. IN A ${CLD_HOST_IP}" # IP host machine cloud
    # local-data: "ha.intra.${INTERNAL_DOMAIN}. IN A ${HA_HOST_IP}" # IP host machine home-automation
    # local-data: "im.intra.${INTERNAL_DOMAIN}. IN A ${IM_HOST_IP}" # IP host machine immich
    local-data: "mm.intra.${INTERNAL_DOMAIN}. IN A ${MM_HOST_IP}" # IP host machine media-management
    local-data: "ms.intra.${INTERNAL_DOMAIN}. IN A ${MS_HOST_IP}" # IP host machine media-server
    # local-data: "nas.intra.${INTERNAL_DOMAIN}. IN A ${NAS_HOST_IP}" # IP host machine nas
    # local-data: "nts.intra.${INTERNAL_DOMAIN}. IN A ${NTS_HOST_IP}" # IP host machine notes
    # local-data: "tdo.intra.${INTERNAL_DOMAIN}. IN A ${TODO_HOST_IP}" # IP host machine todo
    # local-data: "vlt.intra.${INTERNAL_DOMAIN}. IN A ${VLT_HOST_IP}" # IP host machine vault
    # local-data: "vsc.intra.${INTERNAL_DOMAIN}. IN A ${VSC_HOST_IP}" # IP host machine vscode-server
    # local-data: "wb.intra.${INTERNAL_DOMAIN}. IN A ${WB_HOST_IP}" # IP host machine white-board

forward-zone:
    name: "."  # Catch all queries not handled locally 
    forward-addr: 1.1.1.1  # Cloudflare primary DNS
    forward-addr: 8.8.8.8  # Google primary DNS
