server:
    # Listen on all interfaces
    interface: 0.0.0.0
    access-control: 0.0.0.0/0 allow  # Allow public queries by default
    verbosity: 1
    do-not-query-localhost: no

    access-control-view: ${DOCKER_SUBNET}.11/32 intra

    #
    # ==== *.homelab ===
    #
    # Define a local zone for *.homelab with unrestricted access
    
    local-zone: "${INTERNAL_DOMAIN}." redirect
    local-data: "${INTERNAL_DOMAIN}. IN A ${RP_HOST_IP}"  # IP host machine reverse proxy

view:
    name: "intra"

    #
    # ==== *.intra.homelab ===
    #
    # Define a local zone for intra.homelab with restricted access
    local-zone: "intra.${INTERNAL_DOMAIN}." static

    local-data: "ms.intra.${INTERNAL_DOMAIN}. IN A ${MS_HOST_IP}" # IP host machine plex
    local-data: "mm.intra.${INTERNAL_DOMAIN}. IN A ${MM_HOST_IP}" # IP host machine media
    local-data: "nx.intra.${INTERNAL_DOMAIN}. IN A ${NX_HOST_IP}" # IP host machine nextcloud
    local-data: "vw.intra.${INTERNAL_DOMAIN}. IN A ${VW_HOST_IP}" # IP host machine vaultwarden
    # local-data: "ha.intra.${INTERNAL_DOMAIN}. IN A ${HA_HOST_IP}" # IP host machine ha

forward-zone:
    name: "."  # Catch all queries not handled locally 
    forward-addr: 1.1.1.1  # Cloudflare primary DNS
    forward-addr: 8.8.8.8  # Google primary DNS
