---
- name: Configure Proxmox networking and host filtering
  hosts: homelab
  become: true
  vars:
    nameserver_ip: "{{ lookup('env', 'IP_NAMESERVER') | default('192.168.1.254', true) }}"
  tasks:
    - name: Detect physical NIC automatically
      ansible.builtin.set_fact:
        physical_nic: >-
          {{ ansible_facts
            | dict2items
            | selectattr('value.type','defined')
            | selectattr('value.type','eq','ether')
            | rejectattr('key','match','^(vmbr|vnet|tap|lo|docker|br|virbr)')
            | map(attribute='key')
            | list
            | first }}
    - name: Print default interface facts
      debug:
       msg:
          - "Detected physical NIC: {{ physical_nic }}"
          - "ansible_default_ipv4 object: {{ ansible_default_ipv4 }}"
    - name: Write new /etc/network/interfaces
      ansible.builtin.template:
        src: interfaces.j2
        dest: /etc/network/interfaces
        mode: "0644"
      notify: Reload networking
  handlers:
    - name: Flush iptables before networking reload
      ansible.builtin.shell: |
        set -e
        # Set default policies to ACCEPT to avoid lockout during reload
        iptables -P INPUT ACCEPT || true
        iptables -P FORWARD ACCEPT || true
        iptables -P OUTPUT ACCEPT || true

        # Flush and delete chains in all relevant tables
        iptables -F || true
        iptables -X || true
        iptables -t nat -F || true
        iptables -t nat -X || true
        iptables -t mangle -F || true
        iptables -t mangle -X || true
        iptables -t raw -F || true
        iptables -t raw -X || true
      args:
        executable: /bin/bash
      listen: Reload networking

    - name: Reload networking
      become: true
      ansible.builtin.command: ifreload -a
      listen: Reload networking
