### [!] NETWORKING
DOMAIN="${INTERNAL_DOMAIN}"
HOSTNAME="home"
IP_GATEWAY="${infra.IP_GATEWAY}"
IP_NAMESERVER="${infra.IP_NAMESERVER}"
IP_SERVER="${infra.IP_SERVER}"

### [!] HARDWARE
DISK="${DISK}"
KEYBOARD_LAYOUT="${KEYBOARD_LAYOUT}"

### [!] USERS
ROOT_PASSWORD_CRYPTED='password_sha512(${infra.ROOT_PASSWORD})'
USER_PASSWORD_CRYPTED='password_sha512(${infra.USER_HOMELAB_PASSWORD})'

