---
- name: Setup the Jump VM - Refresh SSH keys based on the refresh ssh level
  hosts: jump
  become: true
  vars:
    # Jump VM target repo
    work_dir: "/home/admin/homelab"
    # Controller (Ansible runner) repo root
    controller_repo_root: "{{ inventory_dir }}/../.."

    # opt - refresh ssh: 
    # - level 1 "none": do nothing 
    # - level 2 "new": only copy if they are not present in the target env (default) 
    # - level 3 "full": copy all ssh keys 
    # - level 4 "generate": run the environment/generate_ssh_keys --auto 
    # - level 5 "reset": run the environment/generate_ssh_keys --auto --reset
    refresh_ssh: "{{ lookup('env','REFRESH_SSH') | default('new', true) }}" # none|new|full|generate|reset

  tasks:
    - name: Running refresh_ssh with value
      ansible.builtin.debug:
        var: refresh_ssh
      run_once: true

    ## Copy SSH
    - name: Check if controller config/ssh exists
      ansible.builtin.stat:
        path: "{{ controller_repo_root }}/config/ssh"
      delegate_to: localhost
      run_once: true
      register: st_controller_ssh

    - name: "Copy controller config/ssh -> target/config/ssh (new: no overwrite; full: overwrite)"
      ansible.builtin.copy:
        src: "{{ controller_repo_root }}/config/ssh/"
        dest: "{{ work_dir }}/config/ssh/"
        owner: admin
        group: admin
        mode: "0600"
        force: "{{ (refresh_ssh == 'full') | ternary(true, false) }}"
      when:
        - st_controller_ssh.stat.exists
        - refresh_ssh in ['new','full','generate','reset']

    - name: Check for generate_ssh_keys script in target
      ansible.builtin.stat:
        path: "{{ work_dir }}/environment/generate_ssh_keys.sh"
      register: st_generate_ssh_script

      # generate ssh keys (opt: generate)
    - name: Run environment/generate_ssh_keys --auto (generate)
      ansible.builtin.command:
        cmd: "./generate_ssh_keys.sh --auto"
        chdir: "{{ work_dir }}/environment"
      when:
        - refresh_ssh in ['generate']
        - st_generate_ssh_script.stat.exists
      register: gen_ssh_run
      changed_when: gen_ssh_run.rc == 0

    # reset ssh keys (opt: reset)
    - name: Run environment/generate_ssh_keys --auto --reset (reset)
      ansible.builtin.command:
        cmd: "./generate_ssh_keys.sh --auto --reset"
        chdir: "{{ work_dir }}/environment"
      when:
        - refresh_ssh in ['reset']
        - st_generate_ssh_script.stat.exists
      register: gen_ssh_reset_run
      changed_when: gen_ssh_reset_run.rc == 0

    # SSH keys permissions
    - name: Find ssh *_key files on target
      ansible.builtin.find:
        paths: "{{ work_dir }}/config/ssh/"
        file_type: file
        recurse: yes
        use_regex: yes
        patterns: ".*_key$"
      register: ssh_key_files
      when:
        - st_controller_ssh.stat.exists
        - refresh_ssh in ['new','full','generate','reset']

    - name: Ensure ssh *_key files mode is 0700
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "0700"
        owner: admin
        group: admin
      loop: "{{ ssh_key_files.files | map(attribute='path') | list }}"
      when:
        - ssh_key_files.matched > 0

  post_tasks:
    - name: Assign entire homelab directory to admin user
      ansible.builtin.file:
        path: "{{ work_dir }}"
        owner: admin
        group: admin
        recurse: yes
