---
- name: Pull config files from Jump VM to controller
  hosts: jump
  become: true
  vars:
    work_dir: "/home/admin/homelab"
    controller_repo_root: "{{ inventory_dir }}/../.."
    # opt - pull copy mode:
    # - option 1 "safe": copy only when the file does not exist locally
    # - option 2 "reset": always overwrite local files
    pull_config_mode: "{{ lookup('env','pull_config_mode') | default('safe', true) }}" # safe|reset

  tasks:
    # users-config.toml
    - name: Check if controller config/users-config.toml exists
      ansible.builtin.stat:
        path: "{{ controller_repo_root }}/config/users-config.toml"
      delegate_to: localhost
      run_once: true
      register: st_local_users_config

    - name: Backup controller users-config.toml -> users-config.toml.old
      ansible.builtin.copy:
        src: "{{ controller_repo_root }}/config/users-config.toml"
        dest: "{{ controller_repo_root }}/config/users-config.toml.old"
        mode: "0644"
        force: true
      delegate_to: localhost
      run_once: true
      when:
        - pull_config_mode == 'reset'
        - st_local_users_config.stat.exists

    - name: Pull users-config.toml
      ansible.builtin.fetch:
        src: "{{ work_dir }}/config/users-config.toml"
        dest: "{{ controller_repo_root }}/config/"
        flat: true
      when:
        - pull_config_mode == 'reset' or not st_local_users_config.stat.exists

    # global-config.toml
    - name: Check if controller config/global-config.toml exists
      ansible.builtin.stat:
        path: "{{ controller_repo_root }}/config/global-config.toml"
      delegate_to: localhost
      run_once: true
      register: st_local_global_config

    - name: Backup controller global-config.toml -> global-config.toml.old
      ansible.builtin.copy:
        src: "{{ controller_repo_root }}/config/global-config.toml"
        dest: "{{ controller_repo_root }}/config/global-config.toml.old"
        mode: "0644"
        force: true
      delegate_to: localhost
      run_once: true
      when:
        - pull_config_mode == 'reset'
        - st_local_global_config.stat.exists

    - name: Pull global-config.toml
      ansible.builtin.fetch:
        src: "{{ work_dir }}/config/global-config.toml"
        dest: "{{ controller_repo_root }}/config/"
        flat: true
      when:
        - pull_config_mode == 'reset' or not st_local_global_config.stat.exists

    # global-config.generated.toml
    - name: Check if controller config/global-config.generated.toml exists
      ansible.builtin.stat:
        path: "{{ controller_repo_root }}/config/global-config.generated.toml"
      delegate_to: localhost
      run_once: true
      register: st_local_global_generated

    - name: Backup controller global-config.generated.toml -> global-config.generated.toml.old
      ansible.builtin.copy:
        src: "{{ controller_repo_root }}/config/global-config.generated.toml"
        dest: "{{ controller_repo_root }}/config/global-config.generated.toml.old"
        mode: "0644"
        force: true
      delegate_to: localhost
      run_once: true
      when:
        - pull_config_mode == 'reset'
        - st_local_global_generated.stat.exists

    - name: Pull global-config.generated.toml
      ansible.builtin.fetch:
        src: "{{ work_dir }}/config/global-config.generated.toml"
        dest: "{{ controller_repo_root }}/config/"
        flat: true
      when:
        - pull_config_mode == 'reset' or not st_local_global_generated.stat.exists

    # ssh directory
    - name: Check if target config/ssh exists
      ansible.builtin.stat:
        path: "{{ work_dir }}/config/ssh"
      register: st_target_ssh

    - name: Create archive of remote SSH directory
      ansible.builtin.archive:
        path: "{{ work_dir }}/config/ssh"
        dest: "/tmp/ssh.tar.gz"
      when: st_target_ssh.stat.isdir

    - name: Fetch archive to controller
      ansible.builtin.fetch:
        src: "/tmp/ssh.tar.gz"
        dest: "{{ controller_repo_root }}/config/ssh.tar.gz"
        flat: yes
      when: st_target_ssh.stat.isdir

    - name: Unarchive on controller
      ansible.builtin.unarchive:
        src: "{{ controller_repo_root }}/config/ssh.tar.gz"
        dest: "{{ controller_repo_root }}/config/"
      delegate_to: localhost
      run_once: true
      when: st_target_ssh.stat.isdir

    - name: Cleanup archive on controller
      ansible.builtin.file:
        path: "{{ controller_repo_root }}/config/ssh.tar.gz"
        state: absent
      delegate_to: localhost
      run_once: true
      when: st_target_ssh.stat.isdir

    - name: Cleanup archive on remote
      ansible.builtin.file:
        path: "/tmp/ssh.tar.gz"
        state: absent
      when: st_target_ssh.stat.isdir
